apache/echarts

src/component/toolbox.js
1. IE11不支持<a> download 属性；
2. IE11不能通过window.attachEvent判断了。
=> 修复个小问题：IE11点击保存为图片，鼠标移到图片上提示“点击保存”，但是没有反应

src/component/tooltip.js
同一dom上多次init图表时出现的问题。这个问题在正确使用echarts时并不会出现，此次提交是希望提高echarts的容错能力。
具体问题是：我们在项目中使用带有tooltips的柱状图。如果第一次生成的实例中鼠标hover过（append了tooltips），然而在销毁实例时没有使用dispose方法正确销毁（比如直接将该dom的innerHTML=''）。
那第二次在此dom生成实例时，echarts会自动释放上一个实例。这时由于dom已为空（因为innerHTML设置为''），而echarts还会尝试移除tooltips，导致页面出错，无法生成新的实例。
=> remove tooltips issue

src/component/dataZoom/DataZoomModel.js
FIX https://github.com/ecomfe/echarts/issues/2591
看了半天代码，只改了一个参数，我表示不开心。
=> fixed:DataZoom在mergeOption的时候没有overwrite，导致配置项设置boolan失效

README.md
This package can help embed the interactive charts from ECharts into Shiny applications. 
It's already published on CRAN (https://cran.r-project.org/web/packages/ECharts2Shiny)
=> Added a R package into README(an R interface to ECharts)

src/chart/themeRiver/ThemeRiverView.js
Fixed a typo inside ThemeRiverView.js which caused that users can not define itemStyle:{normal:{}} properties..
=> Fix typo in ThemeRiverView.js

src/chart/funnel/FunnelSeries.js
=> 修复漏斗图tooltip没有百分比的问题

.gitignore, src/chart/funnel/funnelLayout.js
问题描述见这两个 Ticket: #1923 #4966  
为漏斗图的配置项`series[n].sort`增加了两个可选的排序类型（原来仅支持'ascending'和 'descending'）：
```javascript
{
type: 'funnel',
sort: 'none', // 新增加的选项值，表示渲染时不对数据进行排序，与传给 options.series[n].data 的顺序保持一致；
sort: function(a,b){ return a-b; }, // 新增加的选项值，自定义 的排序方法；
sort: 'ascending', // 原有
sort: 'descending', // 默认值
......
}
```
=> 优化漏斗图排序问题： #1923 #4966

src/coord/radar/RadarModel.js
Radar type indicator text allow config to different text color; by setting:
...
radar: [
{
indicator: [
{text:'indicator1',color:'rgba(255, 2, 35, 1)',max:100},
{text:'indicator2',color:'rgba(00, 176, 92, 1)',max:100},
],
}
]
...
=> add Radar indicator can set different text color

src/component/tooltip/TooltipView.js
The tooltip `confine` option currently uses `clientWidth` and `clientHeight` to ensure that the tooltip does not go outside the bounds of the chart. However, `clientWidth` and `clientHeight` do not include the size of the tooltip's border, which can cause the tooltip to go out of bounds. Using `offsetWidth` and `offsetHeight` fixes this issue.
=> use offsetWidth/Height to confine tooltip

src/scale/Time.js
时间跨度大于5天时, 时间坐标标签显示的太少. 这是由于scaleLevels数组中提供的可选项太少导致. 尤其是1d到1w之间跨度太大.
解决办法是补齐缺失的选项.
修复前:
修复后:
=> Fix: 时间跨度大于5天时, 坐标轴label数目太少, 且不均衡.

extension/dataTool/prepareBoxplotData.js, test/boxplot.html
Hello,
I'm using echarts 3.7.1 with Chromium 60.0.3112.113 and Ubuntu 16.04. LTS. 
I slightly modified the Michelson-Morley data
[1, 2, 3, 4, 5, 6, 7, 8, 9, 850, 740, 900, 1070, 930, 850, 950, 980, 980, 880, 1000, 980, 930, 650, 760, 810, 1000, 1000, 960, 960] by adding the numbers 1 to 9 to the first dataset and got this plot:   
Obviously, the whisker in this plot are wrong, because the dataset has no negative values for the speed of light. I rewrote the corresponding JavaScript function in the file echarts/extension/dataTool/prepareBoxplotData.js . With my code, the boxplot looks like this
I kindly request a git pull to fix the bug.
Best wishes,
Denis
=> boxplot whisker fix

src/coord/cartesian/Grid.js
**Pull request for #5148**
Ensures that, when `grid.containLabel` is set to `true`, the bounding rectangle for each axis label is rotated by `axisLabel.rotate` before the union of the bounding rectangles is calculated.
=> #5148: Consider label rotation when grid.containLabel is true

src/coord/axisHelper.js, src/layout/barGrid.js, test/bar-overflow-time-plot.html
I would like to propose the following pull request in reference to issue fixing #4862
针对问题 #4862， 我想提供一个合并请求。
**Summary**
**概述**
Rescale relevant base axis (of time and interval) to account for overflow of bars beyond chart.
伸缩相关的坐标轴（时间和区间）来解决长条溢出图表的问题
**Overview of changes**
**修改简述**
Two files edited.
共修改了两个文件
AxisHelper.js => has additional function to rescale axis
AxisHelper.js => 添加了伸缩坐标的函数
barGrid.js => export calBarWidthAndOffset
barGrid.js => 添加了calBarWidthAndOffset
**Proposed changes**
**所做的修改**
1. If axis is (time or interval) and has more then one bar and is a base axis
=> Recalculate axis min / max to account for bar overflow
如果坐标轴是时间或区间，并且有多个长条，并且次坐标为基本坐标，
那么伸缩坐标的最小最大值来解决长条溢出问题
2. Calculate physical length of current axis
计算现有坐标的物理长度
3. Calculate placement of bars on current …
=> Fix bar overflow issues #4862 Bug fix

README.md
I noticed the leaflet extension in the readme hasn't been updated for a while and the source code is not actually available in that repo. Mine still is a work in progress but the basics are working.
Putting it here will help more people who needs it see it, and hopefully some will also help improve this extension.
=> add resource echarts-leaflet in readme

src/coord/cartesian/Grid.js
The calculation of a grid position with containLabel = true should not take into consideration the labels that are hidden by setting 'axisLabel.show' to false
=> containLabel should omit hidden labels

src/coord/axisHelper.js, test/README.md
Hi @pissang,
I noticed there with the latest release of ECharts 4.0.0 that the fix we had worked on earlier didn't seem to be working. 
It seems during the refactoring the min value was no longer being converted to an absolute value which meant the buffer was not being correctly set on each side.
I have updated src/coord/axisHelper.js to account for this.
I have also updated test/README.md to reference the new build script.
Please let me know if you want any more changes made!
Thanks,
Conor
=> Bar overflow issues #4862. Ensure absolute values are used when calculating overflow

.gitignore, src/component/marker/MarkLineView.js, src/component/marker/markerHelper.js, src/data/List.js, test/scatter-markline.html
There are only 3 [markLine types](http://echarts.baidu.com/option.html#series-scatter.markLine.data.0.type):
- max
- min
- average
- ~median~
But there is another important type in data analysis, called median.
It can also be achieved by customize markLine option after calculate the median locally. But I think `median` should be a build-in markLine type for echarts.
----
Changelog:
1. add `median` markLine supported.
2. add the demo of markLine in scatter named `scatter-markline.html`.
3. update .gitignore.
----
Preview:
=> Add new markline type `median`

src/chart/gauge/GaugeView.js
As described in  #9194 - echarts ignores axisLine.show option. Support for this option added by this commit.
=> axisLine.show option implemented for Gauge

src/chart/graph/GraphView.js
when `series[i].type` is `graph`, series[i].label.rotate is invalid
=> fix #9182 Graph    label.rotate is invalid

src/chart/sunburst/SunburstPiece.js
maybe a idea, check again please
=> fix: #8952 callback function params.color incorrect

src/chart/graph/categoryVisual.js
=> fix #8009 & #5969, symbol symbolSize and opacity setting for category itemStyle in graph

src/chart/pie/PieView.js, src/chart/pie/pieLayout.js
The value of the fan page of the pie chart is less than a certain value. The label and labelLine of this fan page are not displayed.
```javascript
options={
title: {
text: '饼图标题',
left: 16,
textStyle: {
fontSize: 14
}
},
tooltip: {
trigger: 'item',
axisPointer: {
//坐标轴指示器，坐标轴触发有效type: 'shadow'//默认为直线，可选为：'line'|'shadow'
},
extraCssText: 'max-width: 300px; word-break:break-all; white-space: normal'
},
legend: {
data: [
]
},
series: [
{
type: 'pie',
label: {
normal: {
show: true,
limitScale: 0.02//小于2%的，不显示
},
emphasis: {
show: true,
textStyle: {
fontSize: '14',
fontWeight: 'bold'
}
}
},
labelLine: {
lineStyle: {
color: '#D9D9D9'
}
},
data: [
]
}
]
};
```
=> Pie chart adds filterValue parameter

src/component/tooltip/TooltipContent.js
`clientWidth` and `clientHeight` contains padding, so it should be excluded in `getComputedStyle`.
=> fix: exclude padding from tooltip position, since it's included in clientWidth

src/layout/barPolar.js
=> fix(polar): barWidth calculation when stack on multiple polars #9626

.travis.yml, README.md, package.json
ECharts CI status can be seen at https://travis-ci.org/apache/incubator-echarts.
Notice that Apache uses `.org` instead of `.com`.
See #9850 for more discussion on CI stuff.
=> ci: add ci support

src/visual/symbol.js
series->symbol支持函数类型
如果需要每个数据的图形不一样，可以设置为如下格式的回调函数：
`(value: Array|number, params: Object) => number|Array`
eg.
```
symbol: function (value, params) {
return `${symbol}`;
}
```
**注：返回的symbol支持类型同之前**
=> series->symbol支持函数类型，根据需要来设置每个数据的图形

src/model/mixin/textStyle.js, src/util/format.js
Fix  calculate label bounding rect error when rich used 
(e.g., containLabel: true while axisLabel has rich)
=> Fix: calculate label bounding rect error when rich used

src/action/createDataSelectAction.js
Add `seriesId` field in `pieselectchanged` event.
Fix #9830 .
=> fix(pie): add seriesId in pieselectchanged #9830

src/component/axis/AxisBuilder.js, test/axis-name.html
fix: axis name align not working bug #9901
Axis name had no effect.
In this fix, option in `nameTextStyle.align` and `nameTextStyle.verticalAlign` are used to overwrite those computed automatically from `endTextLayout()` and `innerTextLayout()`.
=> fix: axis name align not working bug #9901

src/component/toolbox/feature/SaveAsImage.js
We won't use $a for IE and edge. In addition, there's no `document` object in web worker. So we'd better don't create an element if we don't need to.
Ref: https://github.com/apache/incubator-echarts/issues/9232
=> fix(SaveAsImage): don't create an anchor element if you don't need to

src/component/axis/AxisBuilder.js
* fix bug #9282
Add a defensive statement for `axisModel.getCategories`,  so axisLabel of chart radar can display correctly (cannot trigger event though, which isn't used widely).
It's a temporary solution until axisLabel of chart radar supported in the next release.
=> Temporary solution for chart radar can display axisLabel correctly.

src/component/helper/MapDraw.js
compoundPath and compoundPath.paths in  MapDraw.js set segmentIgnoreThreshold to 1 Manually, so the small segment will be ignored in map series to improve performance.
=> refactor(map): add segment ignore threshold in map draw

src/component/toolbox/ToolboxView.js, test/toolbox-textStyle.html
#10202 Requested a more flexible toolbox label configuring method. This PR fulfills that requirement but the little triangle in the design of https://gitlab.com/gitlab-org/gitlab-ce/issues/57130 is not supported.
Requirement:
Example of what you can get from this PR:
The text color, background color, border radius, text padding can all be configured.
But the small triangle is currently not supported, because we have to add new option entry for that and thus needs further discussion. @Jivanvl Please see if this meets your requirement.
---
In this PR, I added support for several options for `toolbox.emphasis.iconStyle`, namely:
- `textPosition`, `textFill`, `textAlign`: these options were supported but have no effect for settings in  `toolbox.emphasis.iconStyle.xxx` due to a bug and they …
=> feat: add toolbox text style support

src/component/toolbox/ToolboxModel.js, src/component/toolbox/ToolboxView.js, test/toolbox-tooltip.html
To support HTML for toolbox title as mentioned in #10202, I propose in this PR the support of tooltip for toolbox.
This is what you can get with the following option:
```js
option = {
tooltip: {
show: true // include tooltip component for the feature
},
toolbox: {
show: true,
showTitle: false, // hide the default text so they don't overlap each other
feature: {
saveAsImage: {
show: true,
title: 'Save As Image'
},
dataView: {
show: true,
title: 'Data View'
},
},
tooltip: { // same as option.tooltip
show: true,
formatter: function (param) {
return param.title; // which is the same as not setting formatter
},
backgroundColor: '#222',
textStyle: {
fontSize: 12,
},
extraCssText: 'box-shadow: 0 0 3px rgba(0, 0, 0, 0.3);'
}
},
...
}
```
To view the full code, please refer to …
=> Feat: add tooltip support for toolbox

src/component/toolbox/feature/SaveAsImage.js, src/echarts.js, test/toolbox-saveImage-background.html
`toolbox.feature.saveAsImage.connectedBackgroundColor` can be used to set the background color.
Fix #10099.
Document changes are available at https://github.com/ecomfe/echarts-doc/commit/18983da9ab64a61bde69f13b63f1c729a93c2f98 , which should be merged after this PR is accepted.
=> feat: support backgroundColor for connected charts in toolbox

src/echarts.js
fix: use a clearer warning message when initing dom without size #10478
The original warning message when calling `chart.init` without DOM `clientWidth` or `clientHeight` is:
```
Can\'t get DOM width or height.
```
This may cause some confusion to users and they may not know how to fix this.
In this PR, a clearer warning message is provided.
=> fix: use a clearer warning message when initing dom without size #10478

src/component/marker/MarkPointView.js, src/util/symbol.js
当尝试使用这种方式时，控制台报错`symbolType.indexOf is not a function`,我尝试过3.8到4.2.1都没有解决。
```js
symbol: function (value) {
if (value > 200) {
return 'circle'
}
return 'rect'
}
```
[在这个#10440中，](https://github.com/apache/incubator-echarts/issues/10440)，他说已修复，但是我发现并没有修复，可以看这个https://gallery.echartsjs.com/editor.html?c=xJRpq5QC2j&v=2
然后我去看源码，发现`util/symbol.js`中的`createSymbol`方法第一句话是
```js
var isEmpty = symbolType.indexOf('empty') === 0;//当symbolType为function时，他是不存在indexOf方法的，所以会报控制台的错误
```
在`util/symbol.js`的309行增加：
```js
var isFunction = typeof symbolType === 'function'  //判断是否为函数
if (isFunction) {
symbolType = symbolType()
}
```
在`makrt/MarkPointView.js`118行中增加：
```js
// 当symbol是函数的时候给他传递数据
var symbol = itemModel.getShallow('symbol');
if (typeof symbol === 'function') {
symbol = …
```
=> 修复symbol使用Function时控制台提示symbolType.indexOf is not a function

src/data/Graph.js
When data `id` in graph series is in number typed zero `0`, it will use `dataIndex` instead of `id`, which may not be expected by the user since it's expected to use `id` rather than `dataIndex`, like in the case of #10485.
Also, I found that there is no `id` entry in the document in the graph series section. Should I add it?
=> fix: bug when graph data is number typed. Fix #10485

src/component/axisPointer/viewHelper.js, test/tooltip-touch.html
Fix #10569
With `padding: [10, 20, 30, 40]` in [this example](https://gallery.echartsjs.com/editor.html?c=xVszi2WnZ3&comment=0),
Before fix: (wrong)
After fix: (correct)
=> Fix axisPointer label padding not working.

src/component/axisPointer/BaseAxisPointer.js
`elOption.pointer` is `undefined` and accessing `elOption.pointer.style` causes problem.
fix #10570
=> fix: update pointer when type is none, #fix 10570

src/chart/helper/EffectSymbol.js
So effect color can be configable, by default effect color is `itemStyle.color`
```js
{
type: 'effectScatter',
rippleEffect: {
// new option, effect color
color: 'red',
brushType: 'stroke'
}
}
```
=> feat: (effectScatter) add rippleEffect.color

src/echarts.js
Fix and close #10926 .
Calling functions like `chart.resize()` should be warned when `chart.dispose()` was called before.
=> fix: dispose checking for chart instance

src/coord/radar/Radar.js
I recognized something went wrong with radar chart and Axis coordinate when fixing my local charts. Please check this wording issue
=> fix wording coodToData to coordToData

src/util/symbol.js
There is an es6 syntax cause uglify fail.
=> fix: remove es6 syntax

.github/stale.yml
High priority issues should not be marked as stale.
=> doc: update stale config

src/util/graphic.js
=> fix(svg): svg doesn't support addHover; fix #11054

src/chart/pie/PieSeries.js, src/chart/pie/PieView.js, test/pie-animation.html
fix #11029
Using a new option `series-pie.animationTypeUpdate` to support expansion animation for data update, whose value can be `'transition'` (default), or `'expansion'`.
If it's set to be `'transition'`, then the animation will be transforming from the previous data to the updated data, as it behaves with ECharts now.
If it's set to be `'expansion'`, then the animation works like when a pie is created for the first time, which may be useful when the data is fully changed.
=> feat: support expansion animation for data update; fix #11029

src/coord/geo/GeoModel.js
Fix this issue
https://github.com/apache/incubator-echarts/issues/8489
=> Fix #8489 geo.label.formatter is not working

src/chart/candlestick/candlestickLayout.js
The structure of the [largePoints](https://github.com/apache/incubator-echarts/blob/master/src/chart/candlestick/CandlestickView.js#L255) is `[sign, x, yhigh, ylow, sign, x, yhigh, ylow, ...]`. So the length of `largePoints` is 4000 when the count of the `data` in `dataset: {source: data}` is 1000. However, I found the length of `largePoints` is 5000 and the values are zero from 4500 to 4999.
=> fix bug #11101

README.md
contributing doc was moved to root dir. since doc fix branch in apache repo also fall behind master branch ,so merge to apache/incubator-echarts master
=> Fix contributing doc missing issue

test/runTest/compareScreenshot.js
Previous threshold 0.1 is too large. It failed to detect the diff between these two images.
=> test: compare screenshots with smaller threshold in visual regression testing

src/util/graphic.js
fix(graphic): pie highlight not triggering since 5661c6eaaf75b8e98fa9f92348c37842e31c3490
I tested both Canvas and SVG version with `aria-pie.html`, where the bug is reported in the first place, and `lines-stream-not-large.html` with pull request #11156, in which the bug was introduced.
=> fix(graphic): pie highlight not triggering

src/chart/bar/BarView.js, src/layout/barGrid.js
To avoid these two bars been clipped.
=> Bar: Expand clipping area on the value axis or axis with no boundaryGap. 

test/runTest/actions/update.js, test/runTest/store.js
Sort `__meta__.json` by keys to avoid conflicts when two branches are both trying to add actions.
=> test(visual): sort actions meta data by keys

src/coord/Axis.js, test/axis-splitArea.html
Hi, this pull request has two changes:
1. Added two test cases for splitArea color issue. From #10948 #11438 
2. Fix rounding error when calculating ticks. Which will lead to extra ticks being added in the code https://github.com/apache/incubator-echarts/blob/master/src/coord/Axis.js#L337
This bug will lead to wrong splitArea color in a specific resolution in the case from #11438 
(The first color should be green instead of red)
=> fix(axis): fix extra ticks added caused by rounding error. add test cases for splitArea

src/chart/helper/Symbol.js, test/line.html
The [opacity](https://github.com/apache/incubator-echarts/blob/master/src/chart/helper/Symbol.js#L377) of image symbol will be `0` when the legend is unselected. But the `opacity` is still `0` when the legend is selected. The [reason](https://github.com/apache/incubator-echarts/blob/master/src/chart/helper/Symbol.js#L234) is that the style of image symbol isn't reset, so the image symbol will appear when the `opacity` is reset to `null`. Take the emphasis style into consideration,  the `shadowBlur`, `shadowOffsetX`, `shadowOffsetY` and `shadowColor` also should be reset.
=> fix bug #9718

src/model/Global.js, test/dataZoom-extreme.html, test/legend-scroll2plain.html
`Instanceof` can not only judge the direct constructor of the instance object, but also judge all the constructors in the prototype chain. The `componentModel` of scroll legend and the `componentModel` of plain legend both are instance of `ComponentModelClass`, so a new `componentModel` will not be created. The dataZoom also has this problem.
=> fix bug #11000 Type of legend form scroll to plain

test/-cases.js, test/ios13-z-bug.html
The bug is fixed in: https://github.com/ecomfe/zrender/pull/522
IOS13 safari probably has a compositing bug (z order of the canvas and the consequent
dom does not act as expected) when some of the parent dom has
-webkit-overflow-scrolling: touch; and the webpage is longer than one screen and
the canvas is not at the top part of the page.
Check https://bugs.webkit.org/show_bug.cgi?id=203681 for more details.
=> fix: add test case for ios13 z order bug.

src/chart/line/LineView.js
=> fix(line): overflow symbols should render if clip is false #11549

package.json, test/runTest/genReport.js
It is used to generate a all-in-one report file after all the visual test run.
Usage:
```bash
npm run test:visual:report
```
It will generate a `tmp-report.md` file in the `test/runTest` folder. Then you can translate this markdown file to any file you want. Like PDF.
It has a lot of work(mostly UI) to be integrated. But the most wanted feature is to generate a file which can be shared and achieved for the regression testing before releasing. So I think a CLI tool is good enough for this feature.
Maybe later I can add a button on the dashboard to download the generated markdown report file.
=> Add a CLI script to generate visual test report markdown.

src/chart/line/LineView.js, test/clip.html
=> fix(line): axis pointer highlights data outside of chart #11360

src/chart/bar/BaseBarSeries.js, src/chart/custom.js, src/layout/barGrid.js, test/bar-width.html
(1) On value axis, the auto-calculated bar width might be near 0, which make the bar invisible.
So we add option `barMinWidth` (default 1 in category and default null in other coord sys).
(2) The fix #5316 (commit 2823ab502bf1af27c33de6d09729bc287ef0a185) seems not work any more currently.
check the cases in `echarts/test/bar-width.html`. This fix make it works.
=> fix: fix bar width strategy.

src/coord/Axis.js, src/coord/cartesian/Cartesian2D.js
For category type, one data show on window just check if scale contains it's value
Close #11300
=> Fix #11300

src/chart/graph/GraphView.js, src/chart/sankey/SankeyView.js
+ Add an unfocusNodeAdjacency delay execution timer to delay execute the action.  
+ Add focus state make sure to execute the right action.
=> Fix sankey frequent flashing with hovering on the node and edge #11306

src/chart/line/LineView.js, src/visual/seriesColor.js, test/line-style.html
Use the palette color in `line series` when the itemStyle.color. is a callback. And enhance the test case for itemStyle.color and lineStyle.color for `line series`. Enhance #11485.
=> fix: Enhance #11485

src/util/graphic.js
The original logic will never get font configs from the `textStyle` option, and also the `ecModel` doesn't have other font configs except the `textStyle` option.
=> fix get font configs issue

src/component/legend/LegendView.js
Item should be downplayed before unselecting.
=> fix(legend): fix highlight state after inverseselect #11480

src/component/toolbox/ToolboxView.js, src/component/toolbox/feature/MagicType.js, test/toolbox-stack.html
related issue https://github.com/apache/incubator-echarts/issues/11236
new design integrate stack/tile button into one toggle button in toolbox, function spec as follows:
- When stacked state is activated,  status of stack icon would be emphasis, otherwise 'normal'.
- When stacked state is activated, title of stack icon would be 'Tile', otherwise 'Stack'.
- When there's no data/series for this chart, stack feature would not switch between two states.
=> Fix 11236 integrate stack/tile button into one toggle button in toolbox

src/component/axis/AngleAxisView.js
=> fix(polar): fix axis line not display in polar caused by #11705

src/chart/helper/Line.js, src/component/marker/MarkLineModel.js, test/markLine.html
Provides new layouts for markLine labels.
- #11569: Markline position inside grid area
The previous layout design may often cause the markLine labels to collapse.
Provide multiple new layout designs so that labels may not collapse.
Valid values of []() has been changed from `'start', 'middle', 'end'` to `'start', 'middle', 'end', 'insideStartTop', 'insideStartBottom', 'insideMiddleTop', 'insideMiddleBottom', 'insideEndTop', 'insideEndBottom'`.
- test/markLine.html
=> feat(markLine): provide new layouts for markLine labels

src/chart/tree/TreeSeries.js, src/chart/tree/TreeView.js, test/tree-addNode.html, test/tree-polyline.html, test/tree-recurrentRemoveNode.html, test/tree-removeNode.html
+ add `edgeLayout` in the TreeSeries.js.
+ draw the polyline edge in the TreeView.js.
=> Add polyline edge layout for the tree series #7090

src/chart/pie/PieView.js
Fixed issue 11658
开始时候我们有5个州： 幽州, 荆州, 兖州, 益州, 西凉
幽州 是 idx = 0, isSelected = true;
当点击 legend， hide 幽州之后，idx = 0 的就变成了荆州，piePieceProto.updateData will be called 4 times, not 5. 所以 idx 会指错。需要用 getName 来定位 item。
TODO： 未来可以考虑更好的封装，而不是用 index 或者 name 来让 parent 进行操作。不过可能重构工程量较大😆
=> fix https://github.com/apache/incubator-echarts/issues/11658

src/component/helper/MapDraw.js
`TypedArray#slice` method is not exists on IE. Use `Array.prototype.slice` to clone the TypedArray instead.
https://github.com/apache/incubator-echarts/issues/11451
=> fix(map): fix slice is not defined error on typed array. #11451

src/component/marker/markerHelper.js
Fixed issue where in the charts contain stacked data, the markpoint's position is not correct.
#11535 
#11616 
The max,min,avg marker in the stacked bar or line graph with stacked data is misplaced.
Changed markerTypeCalculatorWithExtent function in the markerHelper, let it always use the stacked data(if they have stack) to calculate marker's coordinate, and get the value from the original data.
NA.
=> fix(Markpoint): MarkPoint position with stack line/bar. Close #11535

src/chart/helper/EffectLine.js, test/geo-lines.html
Apply continuity line trail for effectline, currently enable for 'line', 'rect', 'roundRect' symbolType
https://github.com/apache/incubator-echarts/issues/11739
Effect line breaks when zooming in or at low-end device, since symbol is rendered at discrete position
Applying scaled symbol to fill the gap between last position and current one
only enable continuity trail for 'line', 'rect', 'roundRect' symbolType
test/geo-lines.html
=> fix-11739: apply continuity line trail for effectline

src/component/axis/SingleAxisView.js
add `singleAxis.splitArea` support.
#11690 
by [doc](https://echarts.apache.org/zh/option.html#singleAxis.splitArea), singleAxis should support `splitArea` option, actually not.
add `_splitArea` implement for `SingleAxisView`, imitate `CartesianAxisView`.
=> fix: add missing splitArea support for singleAxis #11690

src/component/title.js
fix subpixel optimize with no lineWidth in zrender.
The logic in https://github.com/ecomfe/zrender/pull/557
#11874 #11891
=> fix: tweak 51f836de (fix subpixel optimize with no lineWidth in zrender)

src/chart/candlestick/candlestickVisual.js, src/chart/helper/createRenderPlanner.js, src/stream/Scheduler.js, test/stream-filter2.html
fix candlestick throw error when some series filtered by legend. 
fix #11611
Throw error. see the case in #11611 .
Fix it by null checking. 
But it might not be a best way.
If intending to declare `performRawSeries` in handlers, only
stream-independent (specifically, data item independent) operations can be
performed. Because is a series is filtered, most of the tasks will not
be performed. A stream-dependent operation probably cause wrong biz logic.
Perhaps we should not provide a separate callback for this case instead
of providing the config `performRawSeries`. The stream-dependent operations
and stream-independent operations should better not be mixed.
It can be down in future version because some more tests and check are needed,
now that the …
=> fix: fix candlestick throw error when some series filtered by legend.

src/component/toolbox/feature/SaveAsImage.js, src/echarts.js, test/toolbox-saveImage-background-svg.html
To support saving SVG images with toolbox. Also works for connected charts.
- #11781: Bug: download svg image with toolbox
1. Default suffix of the downloaded file with SVG charts was `.png` if [saveAsImage.type](https://echarts.apache.org/zh/option.html#toolbox.feature.saveAsImage.type) is not set manually, which should be `.svg` because the downloaded file is an SVG file.
2. The downloaded SVG has an error in it and cannot be opened even after changing the file suffix to be `.svg`
3. It didn't work for connected charts.
1. The default suffix is `.svg` if the chart renderer is `'svg'`.
2. No error after the fix.
3. It works for connected charts now and the background is set to be [connectedBackgroundColor](https://echarts.apache.org/zh/option.html#tool …
=> Fix 11781: save svg image with toolbox

src/component/toolbox/ToolboxView.js, src/component/toolbox/feature/MagicType.js
Fixes the toolbox title issue described in #12162 
- #12162 
After toggling magicType icons, titles in other features in toolbox become `[object Object]`. This is becaues the event fired a new title change and it was overwriting all features.
The event also sends which feature to change the title.
NA.
=> fix(toolbox): only change title of requested feature. closes #12162

src/coord/radar/Radar.js, test/radar-axis.html
Fix value may excced axis min caused by https://github.com/apache/incubator-echarts/pull/11841
=> fix(radar): optimize ticks calculation when min/max is not defined.

src/component/visualMap/PiecewiseModel.js
When minOpen is true, index shouldn't increase to 1
Close #12121
NA.
=> Fix: minOpen is true will drop a piece

src/chart/graph/GraphSeries.js
89221c831217f0b17da5f88d6f3c2426ca64ee9a provide new line label position config,
enhanced the original hard code `distance` to `option` configurable.
This PR add default option to graph, to make the the default distance between line label and line the same as before.
=> Fix/graph line label: keep the original distance between line label and line.

src/coord/axisHelper.js, src/echarts.js, test/axis-extrema.html
Use auto calculation when axis min/max's value is null
Close #11829 
NA.
=> Feat: use auto calculate if min /max is null

src/component/helper/MapDraw.js, test/map.html
This bug was introduced by 7cc5cb5b2e105fdf75033c5c6c8ef214L195
Add map animation when zoom and center change.
- #11947: Missing animation when changing zoom and center of geo component
No animation.
Use `updateProps` to set animation.
test/map.html
=> fix(map): map animation when zoom and center change. fix #11947

src/coord/axisHelper.js, src/coord/radar/Radar.js, test/min-max-function.html
The original PR is:  #12215
cf5812f6aad64e433c0de89c62bd0d84b7f3f0cf
Fix from that:
(1) The min/max function call should not be called twice (necessary and probably wrong input params).
(2) `fixMin` `fixMax` should cover function return.
(3) Add more test cases.
=> fix: axis min/max function return null:

src/chart/sunburst/SunburstView.js, src/chart/treemap/TreemapView.js, src/component/title.js, src/util/format.js
open new link by 'blank' has security risk
[Check this artical](https://dev.to/dhilipkmr/why-should-you-use-noopener-beware-of-security-flaws-3i57)
NA.
=> Fix potential security risk

src/chart/helper/createClipPathFromCoordSys.js
Fix clip bug in chromium when chart size over 18000px.
- [11369](https://github.com/apache/incubator-echarts/issues/11369)
=> fix(line): fix line clip bug in chromium

src/coord/calendar/Calendar.js
Fixes calendar chart layout when user is in a timezone with DST
https://github.com/apache/incubator-echarts/issues/12143
https://github.com/apache/incubator-echarts/issues/10430
When user is in a timezone with DST, the last several months of the year on the calendar chart begin to overlap eachother.
The fix is based on the solution from https://github.com/apache/incubator-echarts/issues/10430
There is currently another PR attempting to fix this problem here: https://github.com/apache/incubator-echarts/pull/12081 - however, from testing, it did not appear to correct the problem.
NA.
=> Fix: Calendar fix for DST

src/chart/sunburst/SunburstPiece.js
Fix sunburst not being lifted with higher z2 when mouse hovers on.
Originally reported from https://lists.apache.org/thread.html/r2cd2ec8c9241d87ab2ce2cd472596b4bc31df25d58e5b0a9b66db5ab%40%3Cdev.echarts.apache.org%3E .
Border is not clear owing to the same z2 with other sectors.
Border is clear.
NA.
=> fix(sunburst): lift sunburst with higher z2 on emphasis

src/component/tooltip/TooltipView.js
Add a parameter to `getData` so sankey can have tooltip option 
Close #12006 
Links tooltip was controlled by nodes,
Links has own tooltip option
NA.
=> Feature: add tooltip for edges(links) (#12006)

src/coord/axisHelper.js
Which will cause `max` in axis invalid.
=> fix(axis): fix typo in #12371

src/component/toolbox/feature/SaveAsImage.js
- [✅ ] others
in some micro front-end framework( for examle taobao's qiankun framework), window maybe is a Proxy ,so use document.defaultView instead of it , to solve the saveAsImage error.
before:
after:
=> saveAsImage function, use document.defaultView instead of window

src/component/marker/MarkPointView.js, test/markPoint.html
Fixes #12731 `symbolRotate` for `markPoint` does not work
- #12731
Symbols don't rotate even if we've specified `symbolRotate`.
Symbols will perform the rotation as we specified.
Please refer to `test/markPoint.html`.
=> fix(markPoint): symbolRotate for markPoint does not work.

src/chart/sunburst/SunburstPiece.js, src/chart/sunburst/SunburstSeries.js, src/chart/tree/TreeSeries.js, src/chart/treemap/TreemapSeries.js, src/chart/treemap/treemapVisual.js, src/data/Tree.js, test/sunburst-visualMap.html, test/treemap-simple2.html
Sunburst labels didn't support formatters in `levels`. This PR enables them.
- #12223: 旭日图 levels层级标签formatter不生效
`label.formatter` under `levels` has no effect.
`label.formatter` under `levels` takes effect.
NA.
=> fix(sunburst): enables label formatter in levels #12223

extension-src/bmap/BMapView.js
According to [Coding Standard](https://echarts.apache.org/en/coding-standard.html#language-features), ES5 shouldn't be used. This PR removed related usage.
`Object.keys` which belongs to ES5 is used in source code.
Added a function named `isEmptyObject` as the substitution for `Object.keys`
```js
function isEmptyObject(obj) {
for (var key in obj) {
if (obj.hasOwnProperty(key)) {
return false;
}
}
return true;
}
```
=> fix(bmap): removed ES5 in bmap extension.

src/chart/radar/RadarView.js, test/radar.html
Fixes the bug that `symbolRotate` does not work for `radar` series.
Whatever we set `symbolRotate`, symbol of radar is always facing north.
symbol of radar will perform a rotation as we specify.
Please refer to `test/radar.html`.
=> fix(radar): symbolRotate does not work for radar series.

src/echarts.ts
Provide elapsed time in rendered event.
Usage:
```
chart.on('rendered', function (params) {
console.log(params.elapsedTime);
});
```
Developers find it hard to know how long does it take for each frame when debugging.
Providing `elapsedTime` of each frame in `rendered` event.
Added `params`:
```
chart.on('rendered', function (params) {
console.log(params.elapsedTime);
});
```
NA.
Relies on https://github.com/ecomfe/zrender/pull/570 . Merge after the PR in zrender is merged.
=> feat: provide elapsed time in rendered event

src/chart/bar/PictorialBarSeries.js, src/chart/treemap/treemapLayout.js, src/component/axisPointer/axisTrigger.js, src/component/legend/ScrollableLegendView.js, src/component/visualMap/VisualMapModel.js, src/coord/axisDefault.js, src/data/List.js, src/visual/VisualMapping.js
Replace typos in comments defining something as "defualt".
Comments had sometimes defualt instead of default (inverting au).
Typos are fixed, replacing defualt with default.
Changes only to comments - code did not show these typos.
I hope it's ok to exclude dist (i understand that's only updated by a release?). 
If not let me know.
=> Update comments to not use defualt (fixing typo)

src/component/dataZoom/AxisProxy.ts, src/component/dataZoom/DataZoomModel.ts, src/component/dataZoom/dataZoomProcessor.ts, src/component/dataZoom/helper.ts, src/component/gridSimple.ts, src/coord/axisCommonTypes.ts, src/coord/axisHelper.ts, src/coord/axisModelCommonMixin.ts, src/coord/cartesian/AxisModel.ts, src/coord/cartesian/Grid.ts, src/coord/cartesian/cartesianAxisHelper.ts, src/coord/cartesian/defaultAxisExtentFromData.ts, src/coord/polar/polarCreator.ts, src/coord/radar/Radar.ts, src/coord/scaleRawExtentInfo.ts, src/data/List.ts, src/echarts.ts, src/helper.ts, src/scale/Scale.ts, test/axis-filter-extent.html
+ The "scale extent calculation" is depended by both coord sys and "dataZoom".
So it need to be performed in different stage of workflow and should avoid to call it repleatly or implement it repeatly.
But previously, the "scale extent calculation" is implemented both in `axisHelper.ts` and `dataZoom/AxisProxy.ts`, 
where different code implements similar logic. 
"Scale extent calculation" is based on input of:
(I) option specified min/max/scale (including callback) and 
(II) dataExtent and 
(III) some filter related components like dataZoom.
Currently we need add more filters depends on that axis scale calculation.
e.g., 
(I) one axis min max effect the other axis extent 
(II) custom filter.
So we refactor that "Scale extent calculation" as a reusable …
=> Extent filtered by other axis

src/chart/helper/Symbol.js, src/chart/tree/TreeView.js, test/tree-image2.html
Fixes #12279
Fixes #11860
- #12279
- #11860
The symbols of image type do not display at the first rendering. Please refer to #12279, #11860 for more details.
After creating the instance of `SymbolClz`, update its data immediately but not wait until the next update rendering if the type of symbol is image.
Refer to `test/tree-image2.html` for a test case.
=> fix(tree): the symbols of image type do not display at the first rendering. close #12279.

src/component/title.js
Fixed #12841, which was brought by #12380.
When `sublink` is cliked, a wrong link(should be `sublink`, but `link` in fact) will be opened. 
- #12841
NA.
=> fix(title): incorrect redirect when sublink is clicked.

src/component/tooltip/TooltipContent.js, src/component/tooltip/TooltipRichContent.js, src/component/tooltip/TooltipView.js, test/tooltip-windowResize.html
when alwaysShowContent is true change or rotation window size and restore will hide tooltip
Close #12812
1- display echart tooltip exemple: https://echarts.apache.org/examples/en/editor.html?c=line-tooltip-touch
2- add option 'alwaysShowContent: true' for tooltip
3- click on the chart for display tooltip
4- change window size or rotation
the tooltip move, not corresponding to the selected point position
when alwaysShowContent is true change or rotation window size and restore will hide tooltip
NA.
=> fix: #12812

src/chart/graph/GraphSeries.js, src/chart/graph/circularLayoutHelper.js, src/chart/graph/forceLayout.js, src/chart/graph/simpleLayoutHelper.js, src/chart/helper/createGraphFromNodeEdge.js, src/chart/helper/multipleGraphEdgeHelper.js, src/data/Graph.js, test/graph-mulitple-edges.html
the ```type=graph``` support multiple edges between two nodes 
the ```type=graph``` support multiple edges between two nodes 
#6811
```series > autoCurveness```
```
// if number will set curveness list max length with params
// if function will use the return array as the curveness list 
autoCurveness: 'number | function() {}'
```
graph-mulitple-edges.html
=> feat(graph): graph support multiple edges, for #6811

src/chart/tree/TreeView.js
update line color when update charts
NA.
=> fix(tree) The chart line color is not updated when updating a node's lineStyle

.gitattributes
Currently, the pull-request-size bot calculates the size of PR without excluding the files in `test` directory.
Here I've tried to add a `.gitattributes` file to make bot ignore them.
**Because the `.gitattributes` file is originally used to specify properties for listed files in it for git, I'm not sure whether it will bring something unexpected.**
Ref:
- https://docs.github.com/en/github/administering-a-repository/customizing-how-changed-files-appear-on-github
- https://docs.github.com/en/github/using-git/configuring-git-to-handle-line-endings#per-repository-settings
=> feat(bot): added .gitattributes file to exclude files needed to ignore for pull-request-size bot.

src/chart/line/LineView.ts, src/chart/parallel/ParallelView.ts, src/component/axis/ParallelAxisView.ts, src/component/axis/parallelAxisAction.ts, src/component/dataZoom/SliderZoomView.ts, src/component/dataZoom/roams.ts, src/component/parallel.ts, src/echarts.ts, src/model/Global.ts, src/util/graphic.ts, src/util/types.ts
Currently, we use the `animationUpate` options in series to transit the elements when data updated.
But in the case which user can trigger the update frequently, like dataZoom, resize. The long animation duration may let chart seems to be not responsive. Especially when we changed the default easing from `'cubicOut'` to `'cubicInOut'`.  
So this pull request can let dataZoom and resize pass global animation config through payload. And when series do update, it will use the config in the payload instead of the animation config in the series. It will make the update faster, more responsive, and neater.
=> [5.0] feat(animation): action from dataZoom and resize can override the animation in series.

src/coord/radar/RadarModel.ts, src/helper.ts
Use `mixinAxisModelCommonMethods` to mix radar axis model with `AxisModelCommonMixin`
`AxisBaseModel` don't have `getNeedCrossZero` method
No error
NA.
=> Fix: radar model mixin with  AxisModelCommonMixin

src/processor/dataSample.js
Data sampling doesn't work when `size` in `dataSample` is negative.
NA.
e.g. In `line-large.html` and `largeLine.html`, data sampling doesn't work because `extent[1] - extent[0]` is negative.
Fixed.
NA.
=> fix(dataSample): negative size

src/chart/heatmap/HeatmapView.ts, test/heatmap.html
While rendering data for heatmap, judgement on whether data item will be out of current axis scale extent were implemented, and those items out of visible range will be skiped.
#12969 
As original issue states, yAxis labels will be covered by color blocks (data series) in heatmap when `min` option was applied to `xAxis`. Actually these blocks should not be rendered since they are not in current extent of xAxis.
A judgement before rendering rect for each data item was added to calculate whether it will be in the extent, and rendering will be skipped if it is not in the extent.
This change also passed tests for scale changes cases such as using `dataZoom` control, using data zoom in toolbox, etc.
NA.
I have to admit that it's not a so perfect solution. A …
=> fix(heatmap) Skip rendering for data out of axis content in heatmap (#12969)

src/component/timeline/SliderTimelineView.js, test/timeline-dynamic-series.html
fix the bug which may bring a crash of browser when using dataURI as the icon of timeline control, closes #12867.
- #12867
If users specify `timeline.control.controlStyle.playIcon` for a dataURI, it may lead to a crash of the browser.
Changed the implement of `makeIcon` to `graphic.createIcon` from `graphic.makePath`.
Please refer to `test/timeline-dynamic-series.html`.
N/A.
=> fix(timeline): fix a bug which may bring a crash of browser when using dataURI as icon(#12867).

src/chart/line/LineSeries.ts, src/chart/line/LineView.ts, src/coord/cartesian/GridModel.ts, test/line-boldWhenHover.html
According to the suggested design change in #12931, add a new semantic value `bolder` for `emphasis.lineStyle.width` for line series to specify whether the line should be bolder when it's in emphasis state.
- #12931
The line series won't be bolder to highlight when hovering on it unless users specify `emphasis.lineStyle.width`.
By default, the line series will be bolder when hovering on it. But if users set `emphasis.lineStyle.width` as a specific number manually, it will be bolder as they specified.
Added a new semantic value `bolder` for `emphasis.lineStyle.width` , default value is `bolder`.
Refer to `test/line-boldWhenHover.html`
=> feat: make line bolder when line is in emphasis state, designed by #12931.

src/util/number.ts
Fix a bug that the `parseDate` function can not parse a date string like `2020-07-29 09:2:5`.
The minute/second has only one number, not padding with 0.
Another potential bug about time is mentioned in https://github.com/apache/incubator-echarts/pull/13039#discussion_r462147069
=> fix(util/number): the `parseDate` function failed to parse a date string like `2020-07-29 09:2:5`.

src/chart/bar/BarView.ts, src/util/graphic.ts
Fix interpolation when no data in the first time setOption. Use the data in the current setOption as interpolated value.
=> fix(bar-race): fix interpolation

src/util/styleCompat.ts
There may be a typo in `out.textStrokeWidth = richItem.font`, which should be `out.font= richItem.font`.
NA.
=> fix(util/styleCompat): fix a typo in `convertToEC4RichItem` function.

src/chart/lines/LinesSeries.js, test/lines-mergeOption.html
Fixes the bug that lines series will disappear after `setOption({})`, closes #12836.
- #12836
- #9212
See #12836, #9212
Tweaked `LinesSeries.mergeOption`, removed the code line below
```js
option.data = option.data || [];
```
Refer to `test/lines-mergeOption.html`.
=> fix(lines): lines series shouldn't disappear after `setOption({})`. (#12836)

src/component/toolbox/feature/DataView.js, test/dataset-charts.html
When dataset is used, data view shows NaN.
Close #7533 
NA.
=> Fix dataview show NaN when user use dataset

src/component/toolbox/feature/DataZoom.js, test/dataZoom-toolbox.html
allow user to custom brush style in toolbox.feature.dataZoom
#8964
框选型数据区域缩放组件不能更改选框颜色，在暗色主题下表现不好
允许用户通过配置自定义选框样式
toolbox: {
feature: {
dataZoom: {
show: true,
yAxisIndex: null,
brushStyle: {
borderWidth: 2,
color: 'blue',
opacity: 0.1,
borderColor: '#596A76',
}
},
}
},
NA.
=> feat(dataZoom): custom brush style in toolbox.feature.dataZoom

src/chart/map/MapSeries.js, src/chart/radar/RadarSeries.js, src/component/marker/MarkerModel.js, src/component/tooltip/TooltipContent.js, src/component/tooltip/TooltipRichContent.js, test/tooltip-textStyle.html
Fix bugs with tooltip textStyle with:
A) In `'html'` renderMode:
- Enabling text shadow settings with all series
B) In `'richText'` renderMode:
- Enabling text shadow settings with all series
- Enabling font settings with all series
- Correcting new line for radar and map series and markers
- #12232
NA.
=> fix(tooltip): richText for series-specific formatters #12232

package-lock.json, src/component/tooltip/TooltipHTMLContent.ts
The first time of showing `tooltip` on each chart,  because of `transition`, `tooltip` rise from the bottom. So disable transition on the first time
NA.
=> Optimize: disable tooltip transition at first show

src/chart/themeRiver/ThemeRiverSeries.js, test/themeRiver3.html
Keep the number of layer keys in each layer consistent.
Fixed issue #11948 
Use largest layer array is not enough. Because each layer may have a different key, each layer array is inconsistent after call fixdata. 
Save all the layer keys, and if any layer data lack one of keys, add default data(lack key: value) to layer .
NA.
=> fix(themeRiver): use layer key map rather then largestLayer #11948

src/chart/funnel/FunnelSeries.js, src/chart/funnel/funnelLayout.js, test/funnel.html
Funnel chart support orient API with value vertical(default) or horizontal.
series-funnel.orient: vertical | horizontal
NA.
```javascript
option = {
series: [
{
name:'漏斗图',
type:'funnel',
gap: 3,
left: 300,
right: 300,
orient: 'horizontal', // vertical | horizontal, default value is vertical
label: {
normal: {
position: 'leftTop'
}
},
data:[
{value:60, name:'访问'},
{value:40, name:'咨询'},
{value:20, name:'订单'},
{value:80, name:'点击'},
]
}
]
}
```
=> feat(funnel): funnel chart support orient API

src/chart/helper/Line.js, test/markLine-symbolRotate.html
In Line.js (used by graph and markLine), when rotation is not specified by users, the "auto rotation" rule should not be broken when rendered at the second time (like when drag graph or move dataZoom). 
#12392 support the feature of support user specified symbol rotation in Line.js 
Line.js is used by graph and markLine and might other places.
But when rotation is not specified by users, the "auto rotation" rule should not be broken when rendered at the second time. 
The scenario of "render at the second time" are like dragging force layout graph or move dataZoom.
See the triangle below:
=> fix: recover auto rotation for line symbol.

src/chart/bar/BarView.js
Fix 13009
Switch 'options -> series -> showBackground' from `false` to `true` will no longer throw exceptions. (something like calling `useStyle` from undefined, more detailed described in #13009 )
Switch 'options -> series -> showBackground' from `false` to `true` will throw exceptions.
Switch 'options -> series -> showBackground' from `false` to `true` works well.
No
NA.
=> fix(bar): showBackground bug when update with no previous background elements

src/model/Global.ts
Try to fix a typo in [`src/model/Global.ts`](https://github.com/apache/incubator-echarts/blob/next/src/model/Global.ts#L867)
`seiresIndex` -> `seriesIndex`
I found this typo exists here for ages but I don't know what bug it brought yet.
NA.
=> fix(model/Global): fix a typo.

src/component/tooltip/TooltipView.ts
Fix a tooltip disappearing when tooltip trigger is "axis" and data is refreshed.
Chart with datazoom slider and live update every few seconds. The slider is somewhere in the middle with a fixed value range. When the user hovers over the data, the tooltip with trigger "axis" shows correctly. But as soon as new data is pushed to the chart the tooltip disappears. This PR fixes that.
Tooltip with trigger axis stays when data is refresehd.
NA.
=> fix(tooltip): keep axis tooltip open on refresh

src/component/toolbox/feature/DataView.ts
Fix #13031 and #13086 
#13031 has described such a situation that user has provided `optionToContent` function while has not provided the corresponding `contentToOption` function.
If we think echarts should also work well in this situation, we need to make `contentToOption` function totally optional. (In other words, if user hasn't provided it, bugs like missing series data or showing a list of `undefined` should not happen.)
If user provide `optionToContent` function but has not provided `contentToOption` function, press 'refresh' will lose data and make a list of `undefined` displayed.
Even user has not provided `contentToOption` function, by pressing 'refresh' button also works well.
No
NA.
=> Fix: make `contentToOption` totally optional

src/echarts.js
Don't use `hoverLayerThreshold` in worker
See #13164
NA.
=> fix: partially resolves #13164

.gitignore, src/chart/effectScatter/EffectScatterView.ts, src/chart/helper/LargeSymbolDraw.ts, src/chart/helper/SymbolDraw.ts, src/chart/line/LineView.ts, src/chart/line/helper.ts, src/chart/line/lineAnimationDiff.ts, src/chart/line/poly.ts, src/chart/scatter/ScatterView.ts, src/chart/themeRiver/ThemeRiverView.ts, src/coord/cartesian/Cartesian2D.ts, src/coord/cartesian/Grid.ts, src/data/List.ts, src/data/helper/dataProvider.ts, src/layout/points.ts, src/scale/Scale.ts, src/scale/Time.ts, src/util/vendor.ts, test/area-smooth.html, test/largeLine.html
This pull request include two improvements to line series.
1. Reduce initial render time(and memory cost) up to 10x in the line series with millions of time series data.
2. Improve smooth result in some cases. 
The most important thing did to improve the performance is to use TypedArray instead of normal array as much as possible. It will reduce the heap memory and GC cost significantly.
In this PR we use TypedArray to store the points of polyline and polygons. Also no `setItemLayout` anymore.
It will simplify the transform to a very fast 6x2 multiply and add operations. But it only works for affine transform when axis type is `time` or `value`. So it's mainly for boosting the time series data.
It can avoid creating millions of temporary `Date` object when parsing the time series data. …
=> [5.0] [Performance] Improve large line performance. Improve line smoothing.

extension-src/bmap/BMapCoordSys.ts, extension-src/bmap/BMapModel.ts, extension-src/bmap/BMapView.ts
- Fix a bug mentioned in #13213, which was brought by a typo.
- Migrate changes to the next branch.
- #13213
Customized map style(v2.0) is not working because of a typo in [line 105](https://github.com/apache/incubator-echarts/blob/master/extension-src/bmap/BMapView.js#L105).
Corrected the typo. `newMapStyle2` -> `newMapStyle`
test/bmap.html
=> chore(extension/bmap): migrate changes to next branch and fix a bug brought by a typo.(#13213)

src/chart/line/poly.ts, src/data/List.ts, src/data/helper/dataProvider.ts, src/processor/dataSample.ts, test/sample-compare.html
This pull request is about to remove chunks in List. It makes the storage structure much flatter. And brings less and more maintainable code and faster access to storage.
We fiirst brought chunk into echarts is for reducing the possibility of clone storage in  `appendData`.  But we found the extra cost to access by chunk is much more than the cost it saved from cloning TypedArray. So we decide to remove it.
The following screenshot can demonstrate the performance improvement:
width= "50%"/><img src="https://user-images.githubusercontent.com/841551/94115724-b6883100-fe7c-11ea-8e2f-bded14d14d23.png" 
width= "50%"/>
=> [5.0] [Performance] Remove chunk in List storage

src/chart/sunburst/SunburstSeries.ts, src/chart/sunburst/sunburstLayout.ts
Sunburst series supports corner radius in ECharts, please refer to #13123 & #13378 for more details.
- #13378 (partial)
Added a new option to the sunburst series.
- **cornerRadius** (can be a string/number/string array/number array)
NA.
#13378 - Pie series supports cornerRadius
fe0d94a - Treemap series supports borderRadius
=> [5.0] [Feature] sunburst series supports cornerRadius

src/component/tooltip/TooltipHTMLContent.ts, src/component/tooltip/TooltipModel.ts, src/component/tooltip/TooltipRichContent.ts, src/component/tooltip/TooltipView.ts, test/tooltip-windowResize.html
- Allow users to add some classes to the tooltip dom to override default styles and get the dom by `document.getElementsByClassName`.
- Migrate changes in PR #12834 (relocate tooltip if chart resized)
NA.
The users cannot set some styles by className.
The users can override some styles by specifying className.
Add a new option `className` to `tooltip` component.
Please refer to `test/tooltip-windowResize.html`
=> feat(tooltip): allow adding classes to tooltip DOM and migrate changes to next branch in #12834.

extension-src/bmap/BMapCoordSys.ts, extension-src/bmap/BMapView.ts
Fix #13424, add absolute position to echarts bmap container.
- #13424
Please refer to this demo https://codepen.io/plainheart/pen/ZEbdRdr
=> fix(extension/bmap): fix bmap first layout may be incorrect if container's layout is flex or grid.(#13424)

src/component/legend/ScrollableLegendView.ts, test/legend-scroll2plain.html
Fix legend scroll animation always start at first element, even the page number wasn't 1.
The problem was that legend content group always reset position to first element before animation.
NA.
=> Fix(legend.scroll): scroll animation start position was incorrect

src/component/tooltip/TooltipHTMLContent.ts, src/component/tooltip/TooltipRichContent.ts, src/component/tooltip/TooltipView.ts, src/util/types.ts, test/tooltip-domnode.html
Allows Tooltip to be set with array of DOM Nodes instead of HTML string.
- #13250
When the tooltip is set, you could only pass static HTML content. I am developing an Angular app. Angular – like other web frameworks (e.g Vue, React) – has its own template mechanism to generate DOM nodes and retain control over their contents, to update them dynamically. However, I could not leverage my framework inside echarts tooltip.
A non-framework approach is shown in the test file `tooltip-domnode.html`. That tooltip shows the continuously updating current date.
In my Angular project. I can return `this.viewContainerRef.createEmbeddedView(template, context).rootNodes` from the `EChartOption.Tooltip.Formatter` and my tooltip content will be updated in Angular's …
=> Allow passing of DOM nodes to setContent

src/chart/line/LineView.ts
Don't bolder when the line width in the normal state is 0.
N/A.
If users specify the line width in the normal state as 0, the bolder logic should be skipped.
See `test/line-boldWhenHover.html`
=> fix(line): only bolder when line width in normal state is larger than 0.

src/util/decal.ts, src/util/types.ts, test/decal.html
This PR makes it possible to disable decal with `itemStyle.decal: 'none'`.
Previously, there is no way to disable a certain series or data item with decal, if the aria decal is enabled.
This PR makes it possible to disable decal with `itemStyle.decal: 'none'`.
`test/decal.html`.
=> feat(decal): using "none" to disable decal

src/chart/treemap/TreemapView.ts, src/util/animation.ts, src/util/graphic.ts, test/treemap-option.html
+ ts: remove @ts-nocheck in some of the files in treemap.
+ fix: done/aborted in treemap. 
+ The bug case is: when click treemap to "drill down", and hover another rect to start state-changeing-animation before the drill down animation finished, some of the done/abort callback may not be called and then all of the "click" disabled (by the implementation of `src/util/animation.ts`.	
+ fix: Make `util/graphic` `updateProps` and `initProps` param `cb` listen "aborted". 
Because, at present, all of the cb usage are about "remove el", which are needed in both "done" and "aborted". 
Currently the usage of `cb`: 
+ initProps:    
+ ParallelView     
+ SankeyView     
+ ThemeRiverView 
+ updateProps:     
+ TreeView     
+ custom
=> Fix treemap click bug when animation not finished and state animation triggered.

src/model/referHelper.ts, test/parallel-feature.html
fix: [parallel] fix that the second category parallel axis can not be selectable
=> fix: [parallel] fix that the second category parallel axis can not be selectable

src/util/decal.ts, src/util/types.ts, test/decal.html
Support symbol as array in decal.
`symbol` can only be `string`.
`symbol` can be `string | string[] | string[][]` so that different symbol type can be used for different rows and columns.
`test/decal.html`
=> feat(decal): symbol support array

src/echarts.ts
fix: lazyMode should wake zrender up, otherwise will be nothing rendered
=> fix: lazyMode should wake zrender up, otherwise will be nothing rendered

src/coord/cartesian/Cartesian2D.ts, test/timeline-layout.html
Test case:
test/scatter-markline.html
```js
markLine: {
label: {
position: 'left'
}
}
```
is an invalid value, but exists in this historical file (`test/timeline-layout.html`),
while will be ignored before v5.0 .
But since v5.0, position: 'left' will cause incorrect result.
Should we compat it?
=> fix: markLine (horizontal or vertical) should be displayed after this optimization.

src/component/timeline/SliderTimelineView.ts, test/timeline-layout.html
test case: test/timeline-layout.html (the 2nd case)
=> fix: fix timeline tick symbol displayed at wrong place.

package.json
For some reason. tslib may be installed in the `zrender/node_modules` when installing dependencies. Which may lead to echarts can't find tslib. So we add the same tslib dependencies in echarts.
=> chore: add tslib in dependencies

src/component/tooltip/TooltipView.ts, src/component/tooltip/tooltipMarkup.ts, src/scale/Time.ts, src/util/format.ts, src/util/time.ts, test/timeZone.html
<br>
<br>
+ tooltip should support useUTC by default.
+ Make the param useUTC/isUTC mandatory rather than optional, which enables to check where useUTC is omitted. Theoretically, the result without useUTC can not substitute the result with useUTC.
+ Change the order of the param isUTC and lang of time.format because isUTC is used more.
+ Comment incorrect implementation of `tooltip.formatter: pattern` on time axis temporarily. Because it should ensure:
+ `useUTC` is not forgotten to be set as `true` or `false`. The result based on useUTC are totally different, which should not be omitted.
+ Should not break the original funtion: tooltip.formatter: '{a0} {a1}'
+ Consider `series.encode: {x: 2}`, that is, `param.data[2]` is time axis value.
Test case: …
=> Fix/use UTC and tooltip.formatter on time axis

src/component/dataZoom/SliderZoomView.ts
=> fix: [dataZoom] fix that after dataZoom updated by others (like inside dataZoom), the brush rect does not display.

src/chart/tree/TreeView.ts
Close #13560
`tree` didn't drawn when `symbol`  was `none`
NA.
=> Fix(tree): `symbol` is `none` cannot be skipped

src/chart/bar/BarView.ts, src/chart/bar/PictorialBarView.ts, src/chart/funnel/FunnelView.ts, src/chart/heatmap/HeatmapView.ts, src/chart/helper/Line.ts, src/chart/helper/Symbol.ts, src/chart/pie/PieView.ts, src/chart/radar/RadarView.ts, src/chart/tree/TreeView.ts, src/chart/treemap/TreemapView.ts, src/label/LabelManager.ts, src/label/labelStyle.ts
This PR is about inheriting label opacity from attached element. It's necessary when visualMap set element out of range to `opacity: 0`
Developers can still set `label.opacity` to 1 to override it.
=> fix(label): inherit opacity from attached element

src/chart/bar/BarView.ts, src/scale/Ordinal.ts, test/bar-race.html
When a sorted category axis `max` is greater than data length (which sometimes happens for bar race charts), the axis label has error so the chart cannot be rendered.
With the third test case of `test/bar-race.html`, it gets error and cannot render the chart.
No error.
`test/bar-race.html`
=> fix(axis): when category axis max is greater than data length

src/label/labelStyle.ts
fix: fix that label animation restart when bar realtimeSort change bar orders.
=> fix: fix that label animation restart when bar realtimeSort change bar orders.

src/coord/cartesian/AxisModel.ts
Some cases of line charts and bar charts display no chart.
This is because `categorySortInfo` default value was changed from `[]` to undefined in 84ead77
but `extraOption` did not change accordingly.
To fix the bar/line charts problem with `categorySortInfo` default value.
NA.
=> fix(bar-race): fix default categorySortInfo value bug

src/chart/bar/BarView.ts
If calling `setOption` with `notMerge`, there is no `oldOrder` so accessing `oldOrder[i]` get error. This PR fixes this problem.
Call `setOption` with `realtimeSort` and then call `setOption` with `notMerge` as `true`.
Checking `oldOrder` before accessing `oldOrder[i]`.
NA.
=> fix(bar-race): fix when no oldOrder

src/chart/gauge/GaugeView.ts
#13962 
- pointer.offsetCenter doesn't work without pointer.icon
- add the offsetCenter to default icon of poiner
NA.
=> fix(Gauge): pointer.offsetCenter doesn't work without icon #13962

src/chart/gauge/GaugeView.ts, src/chart/helper/labelHelper.ts, src/chart/line/LineView.ts, src/label/LabelManager.ts, src/label/labelStyle.ts, src/model/mixin/dataFormat.ts, src/util/model.ts, src/util/types.ts
1. Enable gauge detail value animation again. (Broken by some previous commit)
2. Some restrict and clarify of the parameters of method `getFormattedLabel`:
Before:
```js
extendParams?: Partial<CallbackDataParams>
```
After:
```js
extendParams?: {
interpolatedValue: InterpolatableValue
}
```
Because:
1. this feature is only used in value animation case.
2. `CallbackDataParam` is only about the internal logic in one of the implementation of the interface `getFormattedLabel`.
The parameter of `getFormattedLabel` should not depends on some certain implementation.
There is other implementation of it, which need the parameter to have clear meaning.
=> fix: gauge detail value animation broken by some previous commit.

src/loading/default.ts, test/loading.html
- bugfix: the showLoading.fontSize with number type doesn't work  (#13892)
- bugfix: showLoading align center (#13893)
1. show spinner and text
2. only show spinner
3. only show text
- feature: showLoading support fontFamily/fontWeight/fontStyle
#13892 
#13893 
NA.
=> fix(loading): showLoading align center

.eslintrc-common.yaml, src/.eslintrc.yaml, src/core/echarts.ts, src/core/locale.ts, src/data/Source.ts, src/model/globalDefault.ts, src/util/format.ts
Major changes
1. Avoid unexpected usage of `name`. Fix #13983
2. Remove `node`, `browser` env to avoid unexpected usage of global variables, even like `window`. Which may lead to compatible issues in specific environements
=> Fix unexpected global name usage

build/build.js, build/pre-publish.js, package.json, src/component/timeline/SliderTimelineView.ts, src/core/echarts.ts, src/export/api.ts, src/export/api/helper.ts, src/extension.ts, src/label/labelStyle.ts, src/model/Component.ts, src/scale/Scale.ts, src/util/clazz.ts, src/view/Chart.ts, src/view/Component.ts
So extensions like ECharts GL which provide multiple charts and components can also have the new minimal import API.
An example:
```js
// In extension code.
class Scatter3DChartView extends echarts.ChartView {
....
}
class Scatter3DSeriesModel extends echarts.SeriesModel {
....
}
export function Scatter3DChart(registers) {
registers.registerChartView(FooChartView);
}
// In users code
import {use} from 'echarts/core/';
import {Scatter3DChart} from 'echarts-gl/charts';
use([Scatter3DChart]);
```
+  `echarts.helper.createTextStyle`
+  `echarts.helper.enableHoverEmphasis`
=> Provide Better APIs for extensions like ECharts GL, WordCloud, LiquidFill

src/chart/line/LineView.ts, test/line-endLabel.html
`endLabel` options like `rotate` and `offset` were not working for both `normal` and `emphasis` state.
- #13878
```js
emphasis: {
endLabel: {
offset: [0, -20],
rotate: -5
}
}
``` 
This does not work.
It works after fixing.
NA.
`emphasis.distance` is not supported for now. Document changes should be updated.
=> fix(endLabel): emphasis values

src/component/tooltip/TooltipView.ts
fix `TooltipView.ts` bug
- #13996
when the mouse moves to show the tooltip will throw an error, because in the file `src/component/tooltip/TooltipView.ts`, Line 432 `else if` statement always `true`, although`el` value is undefined.
```javascript
else if (el && findEventDispatcher(el, (target) => getECData(target).dataIndex != null), true) {
```
give the correct parameters.
[test/toolbox-tooltip](https://github.com/fajiaopaopao/incubator-echarts/blob/master/test/toolbox-tooltip.html)
=> fix: when mouse on blank area tooltip throw error

src/component/toolbox/feature/SaveAsImage.ts, src/core/echarts.ts
Currently, we are using the default value `1` as the DPR instead of the real device pixel ratio of the user, which will make the exported image blurred in retina devices. To get a clear one, the user has to set the option as follows:
```js
toolbox: {
feature: {
saveAsImage: {
pixelRatio: 2.5 // specific dpr
}
}
}
```
This PR is intended to enable users to export a clearer image without any specific option.
By default, the exported image is blurred in retina devices.
Don't specify the default `pixelRatio` as `1`. Use the `ECharts#getDevicePixelRatio()` method to get the real dpr instead.
Please refer to `test/toolbox-title.html` or any other case related to the toolbox.
=> fix(toolbox): use current device pixel ratio by default for exporting crisp and clear images.

src/data/helper/dataProvider.ts
In dataProvider, when `appendData` with TypedArray source. It will always do a replacement. So we should not add a `start` offset when filling the `List#_storage`  from dataProvider.
It will fix the issue of `scatterGL-gps` example.
=> fix(data): fix wrong data fetch when appendData with TypedArray

src/component/tooltip/TooltipModel.ts
fix: add back the default tooltip textStyle settings. Without those settings, the tooltip text will follow the website settings if user specified `tooltip.formatter`, which is not expected.
=> fix: add back the default tooltip textStyle settings. 

src/chart/pie/PieSeries.ts, tsconfig.json
Fix deprecated typing.
- #14067 Pie label margin doesn't exist on typing
NA.
=> fix(pie): deprecate series[pie].label.margin #14067

src/chart/pie/labelLayout.ts
fix chart avoidLabelOverlap hides label even when there are lot's of free space.
- #13938: Pie chart avoidLabelOverlap hides label even when there are lot's of free space
dx has the direction(1/-1) presentation, if dx < 0; then dx < rA always be true; 
But if (-dx) > rA, there would be square root of negative number. 
`Math.sqrt(dy * dy / (1 - dx * dx / rA / rA))`
rB will get NaN.
When comparing, dx => Math.abs(dx)
NA.
=> fix(pie): pie chart avoidLabelOverlap hides label. close #13938

src/component/dataZoom/SliderZoomView.ts
`path://` prefix is in wrong position
Close #14014
`handleIcon` was base64 might block render
Chart render successfully.
NA.
=> Fix(handleIcon): icon without 'path://' will block

src/chart/pie/PieSeries.ts, src/chart/pie/PieView.ts, test/pie-label.html
Add `showLabelLine` param for `setLabelLineStyle` to control `labelLine` should be drawn or removed.
Close #13871
After second  `setOption`. `labelLine` didn't hide when `position` is `inside`.
`labelLine` was hidden after second `setOption`
The last test case in `pie-label.html`
=> Fix(pie): labelLine is not hidden in some case

src/chart/line/LineView.ts, test/line-endLabel.html
Close #13685
test/line-endLabel.html
=> Fix: endLabel color support 'auto' 'inherit'

src/component/toolbox/feature/DataZoom.ts
fix: error thrown when `toolbox.feature.dataZoom: { show: false, yAxisIndex: false }`. (brought in 5.0)
Fix: #14171
=> fix: error thrown when `toolbox.feature.dataZoom: { show: false, yAxisIndex: false }`

src/component/legend/LegendModel.ts
adds the icon property to LegendComponentOption
https://github.com/apache/echarts/issues/14262
couldn't add a strongly typed legend option object because the icon property didn't exist
add the type for it
Updates the TS types to be in line with the echarts docs https://echarts.apache.org/en/option.html#legend.icon 
NA.
=> Add LegendComponentOption.icon property type

src/core/echarts.ts, src/export/core.ts
For some unknown reason, [vue-echarts#next](https://github.com/ecomfe/vue-echarts/tree/ee12ad9658f3745a6738c3df995fb0b328b35299) will have `Default export of the module has or is using private name` error when generating declarations. It only happens when reexporting wrapped `ECharts#getDataURL`, `ECharts#getConnectedDataURL`, `ECharts#dispatchAction` methods to the vue component.
So in this PR, we export these necessary private types to avoid this issue:
+ `echarts.Color`
+ `echarts.Payload`
+ `echarts.LinearGradientObject`
+ `echarts.RadialGradientObject`
+ `echarts.LinearGradientObject`
+ `echarts.SetOptionOpts`
=> fix(type): exporting more necessary types for generating declarations in the extensions

src/chart/treemap/TreemapView.ts, test/treemap-action.html
This code has been modified in 8c2267d45 (see #11854) and merge into next branch in dd3d83cc4,
but in 58dc3f701 the merge was not correct enough (it cause the drillDownIcon displayed repeatedly in some case).
So fix it according to 8c2267d45.
=> fix treemap display drill-down icon repeatedly.

src/component/marker/MarkLineModel.ts
`string` is a valid type for `markLine.data` because time axis values can be string. This PR adds `string` to its type.
- #14300: MarkLine1DDataItemOption incorrectly defines xAxis as number
Only `number` is supported for MarkLine1DDataItemOption.xAxis.
Set the type to be `number | string`.
NA.
=> fix(markLine): fix axis type in markLine data and close #14300

src/component/marker/MarkAreaView.ts
fix markArea background color disappearing when markArea inclued selected area 
- #13647: When you select a area in the same color markArea, you will find the markArea background color disappear.
when selected area was included in markArea, then point would not meet condition that set allClipped to false. 
add condition that check if rectangle of markArea intersects the rectangle of display area.
NA.
=> fix(markArea): markArea background color disappeared. close #13647

src/export/option.ts
Export component option's typescript union members separately to enable more explicit typed factory functions for config parts.
Since 5.0.1 the `PiecewiseVisualMapOption` interface is no longer available, only the union `VisualMapComponentOption`.  
That's why some of our utilities to build config parts cannot be typed correctly anymore.
```ts
// until version 5.0.0
import { PiecewiseVisualMapOption } from 'echarts/lib/component/visualMap/PiecewiseModel';
export function createCustomVisualMap(options: CustomOptions): PiecewiseVisualMapOption {
const pieces: PiecewiseVisualMapOption['pieces'] = [];
// build pieces...
return {
...customConfig,
pieces,
};
}
```
```ts
// since version 5.0.1
import { VisualMapComponentOption } from 'echarts';
export …
```
=> Export union members of option types separately

src/component/dataZoom/SliderZoomView.ts
fix dataZoom textStyle not effect
fix dataZoom textStyle not effect
#14285 
when set 
NA.
=> fix(dataZoom):fix dataZoom setting no effect

src/chart/sankey/SankeyView.ts, src/export/option.ts
Set `sankey label`  z2 property.
Close #14287 
`sankey-vertical.html`
=> Fix(sankey): sankey label has higher z2

src/util/format.ts
Fix default time axis formatter so that the time template can be used in tooltip.
Wrong tooltip content
Correct tooltip content
NA.
=> fix(tooltip): fix time axis formatter #14470

src/component/axis/AxisBuilder.ts, src/component/brush/BrushModel.ts, src/component/graphic/install.ts, src/component/legend/LegendView.ts, src/component/toolbox/ToolboxModel.ts, src/component/toolbox/ToolboxView.ts, src/component/tooltip/TooltipView.ts, src/util/graphic.ts, src/util/innerStore.ts, src/util/model.ts, src/util/types.ts, test/runTest/actions/__meta__.json, test/tooltip-component.html
+ Make component tooltip inherit cascade correct: itemOption.tooltip -> componentOption.tooltip -> globalOption.tooltip
(previous incorrect cascade: itemOption.tooltip -> globalOption.tooltip
+ Enable trigger component tooltip by 
```js
chart.dispatchAction({ 
type: 'showTip', 
toolboxIndex: 0, 
name: 'someTootboxItemName' 
});
// or 
chart.dispatchAction({ 
type: 'showTip', 
legendId: 'legend_id', 
name: 'someLegendItemName' 
});
```
To make (2) happen, this commit migrate `ECElement['tooltip']` to ECData['tooltipConfig']['option'],
and add other info in ECData['tooltipConfig']:
```ts
interface ECData {
// ...
tooltipConfig?: {
// Used to find component tooltip option, which is used as
// the parent of tooltipConfig.option for cascading.
// If not …
```
=> feature: [tooltip] correct component tooltip cascade and support manually trigger component tooltip.

src/util/styleCompat.ts
fix the color of series label  on custom series not following the color of  bars
- #14092: Series Label on Custom Series not working properly
The color of series label  on custom series followed the last/hovered bar.
I read the comment below and code on v4.9.0 branch. But I'm not sure whether the fix meets requirement of comment below:
Element.ts
```
outsideFill is a color string or left empty.
If a textContent is "inside", its final fill will be picked by this priority:
textContent.style.fill > textConfig.outsideFill > #000
```
txCfg.outsideFill always get 'auto' as default value , the color of series label should follow the  color of  bars.
NA.
=> fix(custom): fix series label on custom series not working properly. close #14092

src/chart/helper/EffectSymbol.ts, src/chart/helper/Line.ts, src/chart/helper/Symbol.ts, src/chart/helper/SymbolDraw.ts, src/component/marker/MarkLineModel.ts, src/component/marker/MarkLineView.ts, src/data/List.ts, src/util/types.ts, src/visual/commonVisualTypes.ts, src/visual/symbol.ts, test/markLine-symbolRotate.html, test/symbol3.html
**1) fix: markLine `symbolOffset` doesn't work bug**
- Resolves #9325
- Resolves #14106
- Resolves #4771
**2) feat: `markLine.symbolRotate` can be an array to specify symbol rotation at the two endpoints.**
- Related #12736, #12392, #12388
**3) feat: add `markLine.symbolKeepAspect` and fix `symbolKeepAspect` doesn't work bug.**
**4) feat: `symbolOffset` can be a callback function**
- Resolves #12495
- #4771
- #9325
- #14106
- #12495
- https://github.com/apache/echarts/pull/12392#issuecomment-611116024
Please refer to `test/markLine-symbolRotate.html` and `test/symbol3.html`.
=> fix(markLine): fix a bug that markLine `symbolOffset` doesn't work and some other issues.

src/chart/line/lineAnimationDiff.ts, test/lines-extraneous.html, test/runTest/actions/lines-extraneous.json
Discards data-points that were erroneously added to the chart during the lines animation.
- #10228
- #11633
- #12164
- #12433
There are multiple issues currently open about this problem and they might all be related.
Add a test to easily reproduce the bug where points are erroneously added to the chart during the lines animation and make a *naive* attempt at fixing it.
This bug happens during line-animations and it makes the chart display some invalid data-points after the animation is complete. 
These erroneous data-points seem to be transient and they seem to go away after some interactions with the chart (e.g.: by manually changing the data-zoom).
This is a screenshot of the bug from the added test case (there are only **two** points in the series …
=> fix(lines): discard extraneous data-points during lines animation

src/component/calendar/CalendarView.ts
fix day label drifting
- #11508: Day label is drifting on the left when calendar range is getting smaller
If orient is horizontal and range changes, the cell will automatically adjust its width.
But the weekly text margin always to be 50% width of cellSize.
I tried to fix it by making daylabel margin always be the cell's height .
NA.
=> fix(Calendar): fix day label drifting. close #11508

src/chart/line/LineView.ts
Fix a bug that the line width will be unexpectedly large because of using a string value. 
- #14591
Convert the type of the line width to `number` before the addition
NA.
=> fix(line): ensure lineWidth is a number before addition in bolder logic

src/chart/helper/Line.ts
Many of the graph cases failed in `test` due to no edgeSymbol. This PR fixes this problem.
This may be a bug raised from #14375 .
5.0.2 (correct)
Current master (wrong)
Back to the result of 5.0.2.
NA.
=> fix(graph): no edge symbol when offset is not defined

src/component/visualMap/PiecewiseModel.ts, src/component/visualMap/VisualMapModel.ts, src/component/visualMap/VisualMapView.ts, test/visualMap-scatter-colorAndSymbol.html
`visualMap[piecewise].itemSymbol` took no effect.
- #5719: itemSymbol in the visualMap (piecewise) can't be set
`visualMap[piecewise].itemSymbol` took no effect.
`visualMap[piecewise].itemSymbol` should be used as default symbol type when `symbol` is not defined in visualMap pieces.
- `test/visualMap-scatter-colorAndSymbol.html`
=> fix(visualMap): use itemSymbol as default symbol type and fix #5719

src/chart/map/MapView.ts, src/component/helper/MapDraw.ts, src/util/symbol.ts
In map series. When `labelLayout` is set. The highlighted labels are still not updated when zoom or pan the charts. Also `ignore` can't be restored when zooming in on the map.
NA.
=> fix(map): fix label layout may not update in map

src/chart/bar/BarView.ts, src/chart/line/LineSeries.ts
Bar chart will eliminate `borderWidth` when calculating rectangle coordinates. But it didn't check if there is `borderColor`. In this PR this will be checked. Also default `borderWidth: 2` is removed in line series.
There is a gap between bar and axis line because borderWidth is considered.
NA.
=> fix(bar): fix bar layout with borderWidth but no borderColor

src/chart/helper/Symbol.ts, src/chart/tree/TreeView.ts, src/chart/treemap/TreemapView.ts, src/data/Tree.ts, src/util/symbol.ts
1. fix treemap upperLabel opacity incorrect. 
2. enhance TS type of `getVisual`.
=> fix: (1) fix treemap upperLabel opacity incorrect. (2) enhance TS type of `getVisual`.

src/component/marker/MarkLineModel.ts
When upgrading the ECharts dependency in Superset from 5.0.2 to 5.1.0, I noticed that `symbolOffset` in `MarkLine1DDataItemOption` is marked as mandatory, while it's optional in `MarkLine2DDataItemOption`. I believe this parameter can be made optional.
- Incorrect type checking
=> fix(markLine): symbolOffset incorrectly marked as mandatory

src/component/helper/MapDraw.ts
Fix #14699 
Fix #14701
Fix #14708 
- #14699
- #14701
- #14708
The tooltip can't show because of missing `seriesIndex` in the inner store of the element of zrender. 
The seriesIndex will be set by `viewBuildCtx.data.setItemGraphicEl(dataIdx, eventTrigger)` in `resetEventTriggerForRegion`.
But `regionGroup` has no children yet when calling `resetEventTriggerForRegion` for the inappropriate invoking order, which causes the `el.traverse(setItemDataAndSeriesIndex, el);` won't be invoked.
Adjust the invoking order.
Please refer to `test/map-default.html`
=> fix(map): ensure children have been added to group before calling `resetEventTriggerForRegion`.

src/chart/pie/PieView.ts, test/pie-label.html
Currently the label line will stay visible on emphasis when changing from outside to inside. This PR fixes this problem and adds a test to show that emphasis works even after changing back and forth.
=> fix(pie): hide labelLine emphasis when inside

.github/workflows/nodejs.yml, build/pre-publish.js, package.json, src/chart/helper/EffectSymbol.ts, src/chart/pie/PieView.ts, src/util/types.ts, test/ut/core/setup.ts, test/ut/index.d.ts, test/ut/jest.config.js, test/ut/tsconfig.json
1. Fix jest failes on `node_modules/zrender`
2. Remove `canvas` from devDependency, which is always failed on install.
3. Not install zrender from GitHub in the workflow. Always test on the version in the dependency.
4. Add DTS check for earlier versions of TypeScript. 
5. Remove template string in the exported type. Avoid type error in the earlier versions of TypeScript. #14716 
6. Cache node_modules in the workflow to speedup the runner.
=> chore: enhance github workflow

package-lock.json, src/chart/map/MapView.ts, src/coord/geo/GeoModel.ts
1. Default to show tooltip on geo component. 
> This is because in 5.1.0 geo component enabled tooltip for supporting SVG but set show to false by default. Which will cause all series using this geo component don't show tooltip by default.
2. Fix the wrong usage of `setState` in the map. Which may have unexpected error logs(only log, not throw an exception).
3. Update package-lock.json to avoid CI failure.
=> fix(geo): fix tooltip don't show on geo component.

src/component/helper/BrushTargetManager.ts, src/coord/CoordinateSystem.ts, src/coord/cartesian/Cartesian2D.ts, src/layout/barGrid.ts, test/brush3.html
It should clamp range when brush, otherwise, range would larger than 1, because brushed area might exceed the last item.
Close #14416 
`brush3.html`
=> Fix(brush): clamp range when brush

src/chart/line/LineSeries.ts
Changes `series: {endLabel: {valueAnimation: bool}}` to be optional, so `valueAnimation` does not have to be specified every time `endLabel` is specified.
Cannot specify `endLabel: {}` without TS error:
>TS2741: Property 'valueAnimation' is missing in type '{}' but required in type 'LineEndLabelOption'.
=> Changed LineEndLabelOption.valueAnimation to be optional.

test/force2.html, test/parallel-aqi.html, test/parallel-nutrients.html, test/runTest/cli.js, test/runTest/client/client.css, test/runTest/client/client.js, test/runTest/client/index.html, test/runTest/genReport.js, test/runTest/server.js, test/runTest/store.js, test/runTest/util.js
This PR enhances visual regression test.
Major changes:
Because we reduced the size of screenshot storage significantly in https://github.com/apache/echarts/pull/14745 . We can now save multiple versions of test run on our disk now. 
We can manage all test runs in the `ALL RUNS` dialog. 
In https://github.com/apache/echarts/pull/14754 we add nightly build for echarts. It publishes the master branch every day.
So we can now choose to compare to the nightly build. Which can minimize the difference between the dev branch and the master branch if we wan't test if the dev branch breaks something.
Just check the nightly build checkbox and choose nightly versions.
If we wan't to share our test result with others. We can generate the report by simply clicking …
=> Enhance visual regression test

src/component/legend/LegendView.ts
Remove unexpected syntax `String.startsWith` from `LegendView` to ensure better compatibility.
This syntax is not supported in IE, so use `lastIndexOf(search, 0) === 0` instead. 
N.A.
The chart cannot be rendered in IE and threw a syntax error about `startsWith`.
Use `lastIndexOf(search, 0) === 0` instead. 
NA.
=> fix(legend): remove unexpected syntax to ensure better compatibility.

src/component/toolbox/ToolboxView.ts, test/toolbox-custom.html
The visibility of the customized toolbox button cannot be controlled by the `show` option.
Fixes #14405
Fixes #14618
- #14405
- #14618
The customized toolbox button is still visible when `show` is set to be `false`.
Please refer to `test/toolbox-custom.html`.
=> fix(toolbox): the `show` option of customized toolbox button does not work.

src/component/dataZoom/AxisProxy.ts, src/component/dataZoom/DataZoomModel.ts
Fixes Type error while using dataZoom.startValue, dataZoom.endValue
- #14412: 
dataZoom.startValue, dataZoom.endValue supports number | string | Date but in types allowing only number. This is leading to error - Type 'string' is not assignable to type 'number'
Now dataZoom.startValue, dataZoom.endValue supports number | string | Date
NA.
=> fix(dataZoom): type fix for startValue and endValue. close #14412

src/chart/tree/TreeSeries.ts, test/tree-setoption-twice.html
Fixed the bug of running setOption twice in tree chart with different data
close #14858
Tree chart error when running setOption twice with different data
Using optional chains
And add one visual test
test/tree-setoption-twice.html
=> fix(tree): error when running setOption twice with diff data

src/component/tooltip/TooltipHTMLContent.ts
Use kebab-case in `transition` property.
`transition: webkitTransform ease 0.3s;` is not valid, use `transition: -webkit-transform ease 0.3s;` instead.
NA.
=> fix(tooltip): use kebab-case in transition property.

src/core/echarts.ts
fix: resize throw error. fix #14846, fix #11395 .
=> fix: error thrown when resize is called after setOption called with lazyUpdate: true. fix #14846, fix #11395 .

test/toolbox-custom.html
loader has been changed from `esl.js` to `simpleRequire.js` in https://github.com/apache/echarts/pull/14894
=> test: fix old esl code in test

src/model/Global.ts, test/ut/spec/model/componentMissing.test.ts
Previously we do component missing check after merged theme. It may cause false alarm. In this PR we brought the check before merging theme.
https://github.com/apache/echarts/issues/14844
=> fix(option): check the missing component before merge theme

src/chart/tree/TreeSeries.ts, test/tree-basic.html
Add tree path info to the tooltip as Treemap.
Fixes #8800 
The path of the tooltip cannot be customized
tree-basic.html
=> feat(tree): add tree path info to tooltip

src/chart/line/LineView.ts
Fix the bug that the label of the temporary symbol is not in front of the line series and area polygon.
- #14541
- #14735
NA.
=> fix(label): ensure the label of the temporary symbol is in front of line and area polygon.

src/chart/custom/install.ts
fix: [custom series] fix null pointer exception when renderItem returns nothing in progressive rendering. Fix #12221
=> fix: [custom series] fix null pointer exception when renderItem returns nothing in progressive rendering.

src/util/types.ts
fix tooltip position callback return types
- #15030 
change the return type to `Array<number | string>`
NA.
=> fix(tooltip): position callback return type. close #15030

src/chart/line/LineSeries.ts, src/chart/line/LineView.ts, test/line-endLabel.html
fix(endLabel): endLabel should be displayed if show is true in other states #14441
If `endLabel.show` is `false`, endLabel will not show on emphasis even when there is `emphasis.endLabel.show: true`.
- #14441: emphasis endlabel does not work
End label not show on emphasis
End label show on emphasis
NA.
=> fix(endLabel): endLabel should be displayed if show is true 

src/chart/pie/PieSeries.ts
v5 doesn't set the default value for the border of the sector. To fix #15021, the PR is intended to change the default `borderJoin` to `round`. (Note that v4 uses `bevel` as the default value).
- #15021
NA.
=> fix(pie): change the default borderJoin to `round`

src/chart/map/MapSeries.ts, src/chart/pie/PieSeries.ts
fix the wrong type for `PieSeries` data and `MapSeries` data
- #15143
NA.
=> fix(type): fix wrong type for PieSeries data and MapSeries data.

src/chart/treemap/TreemapView.ts, test/treemap-simple.html
If treemap label is set to not show, then just return it
Close #15140 15140
NA.
=> fix(treemap): label.show=false will throw error

src/chart/sankey/SankeySeries.ts, test/sankey-series-nodes.html
fix dragger bug for sankey when series data key name is nodes。
in the no fixed version, when series data key name is "nodes"（which is supported according to official docs）, the draggable effect is only applied to nodes, and the node is splited from edges
fix dragger bug for sankey when series data key name is nodes。
when series data key name is "nodes"（which is supported according to official docs）, the draggable effect is only applied to nodes, and the node is splited from edges
in the no fixed version, when series data key name is "nodes"（which is supported according to official docs）, the draggable effect is only applied to nodes, and the node is splited from edges
const nodes = this.option.data || this.option.nodes;        
const dataItem = …
=> fix(sankey): fix dragger bug for sankey when series data key name is nodes

src/chart/pie/PieSeries.ts, src/chart/pie/PieView.ts, src/chart/pie/install.ts, src/chart/pie/pieLayout.ts, src/processor/dataFilter.ts, src/processor/negativeDataFilter.ts, test/pie-minus-value.html, test/pie-negative-value.html
Support minus value in Pie Chart.
- #15055
the minus value slice fillup the entire pie chart;
NA.
add test file: `pie-minus-value.html` in test folder;
=> feat: pie-chart support negative value

src/component/timeline/timelineAction.ts, test/timeline-event.html
`timelinePlayChanged` event is fired when timeline paused, so it should be fired when play to the end when not looping.
This PR makes it fires this event.
#14588 
When `loop` is `false` and timeline plays to the end, no event is fired.
When `loop` is `false` and timeline plays to the end, `timelinePlayChanged` event is fired.
NA.
=> fix(timeline): trigger timelineplaychange event when play to the end

src/coord/geo/geoTypes.ts
Wrong type for svg handling
export type GeoSVGSourceInput = 'string' | Document | SVGElement;
export type GeoSVGSourceInput = string | Document | SVGElement;
NA.
=> fix(dts): Wrong type for svg handling in .d.ts. close #15262

src/chart/helper/pieHelper.ts, src/chart/pie/PieView.ts, src/chart/sunburst/SunburstPiece.ts, src/chart/treemap/TreemapView.ts
Fix the bug that `borderRadius` can't be reset in pie series and sunburst series when setting it to `null`.
- #15242
`borderRadius` doesn't be removed when setting it to `null` or `undefined`.
Set `borderRadius` to `0` if it's `null` or `undefined`.
NA.
=> fix(pie/sunburst): fix `borderRadius` can't be reset in pie series and sunburst series when setting it to `null` or `undefined`

src/chart/treemap/TreemapView.ts, test/treemap-setOption-twice-noAnimation.html
When `animation` is set to `false` on `treemap`, `renderFinally()` isn't called when calling `setOption` for the second time.
This PR makes sure `renderFinally()` is always called even if `animation` is disabled.
- closes #15282 
In this screenshot, Alexia and Beth should have been removed (they were present in the first option, but were removed in the second option):
After the change, the names are removed correctly when calling `setOption` again.
=> fix(treemap): remove old nodes on disabled animation

src/coord/geo/Geo.ts, src/coord/geo/geoCreator.ts, src/coord/polar/Polar.ts, src/coord/polar/polarCreator.ts, src/coord/single/Single.ts, src/coord/single/singleCreator.ts
Currently `echarts.getCoordinateSystemDimensions` will have error because the dimensions property is undefined in most of the coordinate systems since 5.0 refactoring. It will break 3rd lib like echarts-gl
=> fix(coord): fix coord dimension undefined for 3rd libs

src/chart/bar/BaseBarSeries.ts
fix no function 'clampData' error in 'getMarkerPosition'  method of BaseBarSeriesModel
fix no function 'clampData' error in 'getMarkerPosition'  method of BaseBarSeriesModel
[Issues 15109](https://github.com/apache/echarts/issues/15109)
In that example will generate an error message of 'clampData is not a function'
Add an additonal judgement on 'clampData'
NA.
=> fix(type): there is no function 'clampData' error in 'getMarkerPosition' 

src/util/types.ts
添加一个类型
close #15197
#15197
在SeriesOnPolarOptionMixin添加了类型polarIndex?: number
NA.
=> fix(type): there is no polarIndex when coordinate of series is polar

src/chart/bar/BarView.ts
#15182 enables user to set the polar bar labels to be `'middle'`. But color may not have enough contrast to the background. In this PR, we set the text to be `inside` when position is `'middle'` for polar bars.
=> fix(bar): set label to be inside when position is middle

src/chart/gauge/GaugeView.ts
Update guage label `z2`.
Close #15195
NA.
=> fix(gauge): guage detail label should be on top

src/chart/bar/BarSeries.ts, src/chart/bar/BarView.ts
Check existence of `label`
Open `test/bar-background.html`, an error will throw
`test/bar-background.html`
=> Fix(polar): polar would throw error if no label

src/chart/effectScatter/EffectScatterSeries.ts, src/chart/helper/EffectSymbol.ts, src/chart/helper/SymbolDraw.ts, test/effectScatter.html
Allow configuring the count of ripple effect in `effectScatter` series.
- #15252
The count of ripple effect is hard-coded `3`.
Make ripple effect count configurable. `3` by default.
Add a new option `count` into `rippleEffect` option.
Please refer to `effectScatter.html`
=> feat(effectScatter): make ripple effect count configurable

src/component/tooltip/TooltipHTMLContent.ts, src/component/tooltip/TooltipRichContent.ts, src/component/tooltip/TooltipView.ts, src/util/types.ts, test/tooltip-domnode.html
1) fix(tooltip): tooltip should show DOM content instead of the string [object HTMLSpanElement], resolves #15307.
2) fix(tooltip): should clear the DOM content if user-specified content is null, resolves #14832. Related previous commit: https://github.com/apache/echarts/pull/12947/commits/3ddb125af1870c233b5d3d8c345bdd17015851eb
3) feat(tooltip): formatter can be HTMLElement. (only string/HTMLElement array previously)
4) chore(tooltip): don't show arrow when empty.
- #15307
- #14832
1. Tooltip shows `[object HTMLSpanElement]` instead of expected DOM content.
2. Tooltip doesn't hide when content is null.
1. Tooltip shows DOM content instead of the string `[object HTMLSpanElement]`
2. Hide tooltip when content is null
Tooltip formatted now accepts single …
=> fix(tooltip): tooltip should show DOM content instead of the string [object HTMLSpanElement]

src/chart/gauge/GaugeView.ts, src/data/List.ts, src/util/innerStore.ts
Clicking on the progress in the gauge chart you can get an event
#14655 
Add data index and series index for indexing the data by element in gauge
Useful in tooltip
NA.
=> feat(gauge): Add data index and series index for indexing the data

src/chart/sankey/SankeyView.ts, test/sankey.html
Sankey line's gradient color should folllow orient.
Close #15358
`sankey.html`
=> fix(sankey): gradient should follow orient

src/chart/helper/whiskerBoxCommon.ts, test/candlestick-case.html, test/runTest/actions/__meta__.json, test/runTest/actions/candlestick-case.json
Previously candlestick will pick the value item from the data object when clone. Which will lose itemStyle and other configurations. Now it changes to clone the whole object
#15017
=> fix(candlestick): fix style lost after update

src/chart/tree/TreeView.ts, test/tree-basic.html
https://github.com/apache/echarts/issues/15217
The original logic misses the condition when the root node is changed to its child.
In this condition, the edge between the root node and its child node should be removed;
NA.
=> fix: root node related edge not removed when update data

src/component/tooltip/TooltipView.ts
https://github.com/apache/echarts/issues/15188
Originally, when we update the series' data, the shown tooltip will not update until we move the mouse.
After fixing, the tooltip will update, like below:
(the series data changed in the background 2 seconds after tooltip shows)
Originally the `TooltipView` only checks if the series data's size changed, if the user didn't change size but the value in-place, the tooltip will not update.
=> fix: hovered tooltip not update when options' series data changed

src/chart/treemap/TreemapSeries.ts
Use more specific `treeAncestors` to replace the original `treePathInfo`. `path` can be used to represent from one arbitrary node to another arbitrary node.
Related PR: https://github.com/apache/echarts/pull/14957
NA.
=> treemap: use treeAncestors in callback params

src/chart/radar/RadarSeries.ts, test/radar4.html
Set `lineStyle.join` of radar series to be `'round'` by default to solve the unexpected joint problem.
- #13201
Unexpected angle outside of the radar area at the joint position.
Nothing outside the radar area.
NA.
=> fix(radar): lineStyle.join default round #13201

src/chart/line/LineView.ts, test/linear-gradient.html
Resolves #15407. When `visualMap` is enabled, the line color is unexpected.
- #15407
Revert the change brought by #14602 in `LineView.ts` and normalize the infinite value
https://github.com/apache/echarts/blob/cf7c4efc5c33961e1e932c450e2c16073feaa8fc/src/chart/line/LineView.ts#L246
Please refer to `test/linear-gradient.html`.
=> fix(line): normalize the infinite value when calculating the visual gradient.

src/core/echarts.ts
This PR does a small change on the dispose method. It will reduce the memory cost when the project still holds the ECharts instance after it's disposed.
=> reduce memory when chart instance is still hold after dispose

src/util/number.ts, test/ut/spec/util/number.test.ts
This is a re-commit for original PR #13227 . I didn't modify the original one because due to some reason I can not find my original branch.
The PR updated way of parsing 7th part of date string from simply treat it as milliseconds to pick first 3 digits as milliseconds to avoid unexpected result when backend API return date string with precision of microseconds.
#13195 
Though 3 digits milliseconds is widely used in most situations, some date formatter will return date string 6 digit microseconds (`yyyy-MM-ddTHH:mm:ss.micros`) . ECharts will treat micro seconds as milliseconds when parsing DateTime string and cause unexpected result.
Keep conistent with default constructor of JavaScript Date - only pick first 3 digits when the length of input part …
=> Fix #13195 - Update way of parsing date

src/util/time.ts
时间轴label的默认格式在时间点是分钟时为24小时制，毫秒时为12小时制。时间点间隔较小时显示有问题
默认时间格式统一改为24小时制
Close #15426
NA.
=> fix(xAxis): fix hour format at millisecond unit. close #15426

src/util/time.ts
Get milliseconds wrongly
Get milliseconds correctly
Fixes #15426
NA.
=> fix 15426:milliseconds format

src/core/echarts.ts
add some types
ref: #15486
NA.
=> refactor(types): add some initial configuration types #15486

src/component/tooltip/TooltipHTMLContent.ts, src/component/tooltip/TooltipRichContent.ts, src/component/tooltip/TooltipView.ts
1) tweak the calculation of tooltip offset to make it look not so near to the target element. Appreciated it if there is a better solution.
2) remove unnecessary `getOuterSize` method beacuse `getSize` is now using `offsetWidth/offsetHeight` that contains the `borderWidth`. (Please ensure it has no side effect)
- #14393
Please refer to `scatter.html` or `new-tooltip.html`
=> fix(tooltip): tweak the calculation of tooltip offset to make it look not so near to the target element.

.asf.yaml, .github/workflows/nightly-next.yml, build/prepareNightly.js
We are trying to improve our workflow. Features of the next minor/major version will be included in the next branch before it's merged into master. This pull request is for publishing the nightly version of next branch and add next branch to protected branches.
=> chore: add nightly publish for next branch

src/chart/line/LineView.ts, test/line-animation.html
Line clipping animation was skipped if calling setOption when the first clipping animation is not done.
#15581
```
option = {
xAxis: {
type: 'category',
boundaryGap: false,
data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
},
yAxis: {
type: 'value'
},
series: [{
data: [820, 932, 901, 934, 1290, 1330, 1320],
type: 'line',
areaStyle: {}
}],
animationDuration: 5000,
animationDurationUpdate: 5000
};
setTimeout(function() {
myChart.setOption(option);
}, 1000);
```
Clipping animation should be continued.
NA.
=> fix(line): not stop existing expand animation when update.

src/component/axis/AxisBuilder.ts, src/coord/axisTickLabelBuilder.ts, src/label/labelLayoutHelper.ts, src/util/types.ts
This PR fixes the overlapping labels in the Time Axis.
- https://github.com/apache/echarts/issues/14266
| Before  | After |
| ------- | ----- |
| <img width="600" alt="Screenshot 2021-08-23 at 13 22 15" src="https://user-images.githubusercontent.com/3321893/130433229-1d947bfe-57b3-40cb-8160-807d2a3db1e7.png"> | <img width="600" alt="Screenshot 2021-08-23 at 13 21 54" src="https://user-images.githubusercontent.com/3321893/130433254-1e44f5f0-98a1-4583-8733-e4b3abcd075c.png"> |
NA.
=> Fix: time axis overlapped labels

src/component/marker/MarkAreaView.ts, src/component/marker/MarkLineView.ts, src/component/marker/MarkPointView.ts, src/component/marker/markerHelper.ts, test/marker-case.html
Fix MarkLine/MarkPoint/MarkArea do not work on time axis if input string time format. 
Fix #15675 .
MarkLine/MarkPoint/MarkArea do not work on time axis if input string time format. 
It brought by https://github.com/apache/echarts/pull/15355, 
where 
```ts
const dataCtors = {
'float': CtorFloat64Array,
'int': CtorInt32Array,
'ordinal': Array,
'number': Array,
// original time is Array, not changed to TypedArray.
'time': CtorFloat64Array
} as const;
```
Displayed as before.
=> fix: Fix MarkLine/MarkPoint/MarkArea do not work on time axis if input string time format

src/chart/sunburst/SunburstSeries.ts, src/chart/sunburst/sunburstLayout.ts
Some sunburst examples uses `series.levels.r` and `series.levels.r0` but this option is not exposed in the document. After further examination, we found the original implementation supports `series.data.r` but we don't find the necessary scenario for this by now.  And `radius` typed in `number | number[]` may be a better option name than `r` and `r0` to be consistent with Pie series.
So this PR fixes this problem and exposes `series.levels.radius` to developers.
Tested and passed all `sunburst*` cases.
=> fix(sunburst): radius in levels

src/component/axis/AxisBuilder.ts, src/coord/axisCommonTypes.ts, test/timeScale.html
Use `axisLabel.hideOverlap` to control the overlapping strategy for labels of xAxis. To avoid potential breaking change if we force to hide these overlapped labels in https://github.com/apache/echarts/pull/15583 . Like in the following case, 
It can be accepted if we display all the labels. But the new strategy(on the right) will hide these slightly overlapped labels.
=> feat(axis): add axisLabel.hideOverlap

src/component/legend/LegendModel.ts, src/component/legend/LegendView.ts, test/runTest/server.js
Add back removed `symbolKeepAspect` option
https://github.com/apache/echarts/issues/15717
=> fix(legend): add back symbolKeepAspect. optimize code logic.

src/export/option.ts
Previously we can't use TypeScript declaration merging feature to extend our `SeriesOption` in the extensions like echarts-wordcloud because it's a union type.
This PR adds an interface `RegisteredSeriesOption`. It can be extended with new types of series. `SeriesOption` will pick all its values and get a union type.
```ts
import echarts from 'echarts';
declare module 'echarts/types/dist/echarts' {
interface RegisteredSeriesOption {
wordCloud: WordCloudSeriesOption
}
}
```
=> feat(type): provide ability to extend series option

src/chart/line/LineSeries.ts
Revert the default design "make line bolder in the emphasis state" brought in v5.0
- #15352
See #15352 for more details
NA.
=> revert(line): revert the default design "make line bolder in the emphasis state"

src/visual/aria.ts, test/aria-pie.html
Fix aria labels with dataset.
#15734
Aria label displayed as `[object object]`.
Aria label displayed as `Amount used, 1699`.
NA.
=> fix(aria): fix aria labels with dataset #15734

src/coord/axisCommonTypes.ts, src/coord/axisDefault.ts, src/coord/axisModelCommonMixin.ts, src/coord/cartesian/AxisModel.ts, src/coord/scaleRawExtentInfo.ts, test/logScale.html
According to [doc](https://echarts.apache.org/en/option.html#yAxis.scale)
In `catersain`, only `value` axis can have `scale`.
- Close #10174
NA.
=> fix(axis): only `value` has `scale` in cartesian

src/chart/helper/createSeriesData.ts
**Before**
**After**
#15757
when all value are null, `isNeedCompleteOrdinalData` still should  be true.
NA.
=> fix: should show tooltip when all value are null

src/component/axisPointer/BaseAxisPointer.ts, src/component/dataZoom/SliderZoomView.ts, src/component/dataZoom/roams.ts, src/component/parallel/ParallelView.ts, src/util/throttle.ts
1. Avoid shadow re-render in slider dataZoom when roaming on the chart.
2. Clear throttle timeouts when disposing.
https://github.com/apache/echarts/issues/15409
=> [fix] dataZoom: optimize shadow render performance when roaming.

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
=> fix typo in issue form

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
=> chore: improve issue template description

src/chart/bar/PictorialBarView.ts, test/pictorial-zero-value-offset.html
fix zero data in pictorialbar can't render correct, when the borderWidth be setted.
- #12789
I'm not exactly sure what `pxSign` really means, but it looks like a direction.
when data is zero, then boundingLength is zero, `pxSign` will be zero, and then symbolScale will be zero too, and if `borderWidth` setted and not zero,  the `valueLineWidth` will be NaN.
`pxSign` will be part of the denominator somewhere else, so it shouldn't be 0
NA.
=> fix(pictorialBar): Fixed a problem with rendering incorrectly when data is 0 and `borderWidth` is set to a non-0 value

src/component/tooltip/TooltipHTMLContent.ts, src/component/tooltip/TooltipView.ts, test/tooltip-lag-glitch.html
Fix tooltip lag issue when transition is disabled, resolves #16101.
- #16101
We throttled the `updatePosition` function of tooltip in #15683 to solve the **_shake_** and **_lag_** issue(raised by #14965) in Chrome(with DevTools open) and Firefox. But as #16101 described,  the tooltip will be laggy because of the `50ms` interval when `transitionDuration` is `0`.
Refer to #16101, #16091 for more details.
Throttle it only when `transition` is enabled.
Please refer to `test/tooltip-lag-glitch.html`.
=> fix(tooltip): fix tooltip lag issue when transition is disabled. (#16101)

src/util/shape/sausage.ts
This PR optimize the sausage shape by avoiding creating subpaths with `moveTo` command. It can improve the visual effect of morphing significantly.
Vertices are not matched when doing one-one morphing.
Vertices are matched perfectly.
N.A.
=> fix(bar): avoid creating subpaths in the sausage shape

src/animation/universalTransition.ts
Fix opacity wrong when using clone divideShape in universalTransition
N.A.
=> Fix opacity wrong when using clone divideShape in universalTransition

src/chart/candlestick/candlestickLayout.ts, src/layout/barGrid.ts
Use common helper `createFloat32Array`  to reduce the redundant logic about the large array creation.
=> fix: use common helper `createFloat32Array` to simplify the large array creation.

src/core/echarts.ts, test/ssr-animaiton-wave.html
Add `useViewBox` opt in `renderToSVGString` method to make the generated SVG responsive.
Related PR: https://github.com/apache/echarts/pull/15880#issue-1026012150
https://github.com/apache/echarts/issues/16127#issuecomment-983514232
The generated SVG has no [viewBox](https://developer.mozilla.org/zh-CN/docs/Web/SVG/Attribute/viewBox) attribute and is not responsive.
Use a `useViewBox` opt (default to be true) to add [viewBox](https://developer.mozilla.org/zh-CN/docs/Web/SVG/Attribute/viewBox) attribute. It's responsive now when `width` and `height` are changed.
This allows use to configure `width` and `height` in the CSS.
```css
.chart svg {
width: 100%;
height: 100%;
}
```
=> feat(ssr): add useViewBox opts in renderToSVGString

build/build.js, build/pre-publish.js, package-lock.json, package.json, test/browser-esm-partial.html, test/browser-esm-partial2.html, test/browser-esm2.html
As discussed in https://github.com/apache/echarts/issues/16054. This PR trys to add an extra transform step to add `.js` extension to the import statement after `lib` is generated. 
So before the statement is:
```ts
import * as zrender from 'zrender/lib/zrender';
```
Now it becomes:
```ts
import * as zrender from 'zrender/lib/zrender.js';
```
So specific modules in the `lib` can be imported in the browsers more conveniently.
Still there some required steps needs to be done before we actually importing the modules:
1. For the modules from dependencies. Import map need to be configured.
```html
<script type="importmap">
{
"imports": {
"echarts/": "https://unpkg.com/echarts@latest/",
"zrender/": "https://unpkg.com/zrender@latest/",
"tslib": …
```
=> add .js extension in the import statement

src/chart/graph/install.ts, src/chart/treemap/treemapAction.ts, src/component/brush/install.ts, src/component/helper/interactionMutex.ts, src/component/tooltip/install.ts
Some places are defining the same `noop` function, that's unnecessary. This PR is to reuse the `noop` function from `zrender` util to reduce redundant code.
=> chore: reuse noop function from zrender util to reduce redundant code.

src/chart/map/MapView.ts, test/map-china.html
For `map` series, some labels won't be shown when `legend` is enabled and no label formatter specified.
- #15649
Please refer to the last test case in `test/map-china.html`.
=> fix(map): some labels won't be shown when legend is enabled and no label formatter specified.

src/data/helper/linkSeriesData.ts, src/util/states.ts, src/view/Chart.ts, test/graph-edge-highlight.html
Added property configuration to specify edge highlighting
Source from this issue: https://github.com/apache/echarts/issues/16134#issuecomment-997340280, need to solve the problem of highlighting on the specified side
According to the original method "highlight" of the highlighted node, pass in the dataType property in the payload
```js
echartInstance.dispatchAction({ type: 'highlight', dataType: 'edge | node', dataIndex: number | number[] })
```
=> Support using dataType param to specify edge highlighting

src/coord/polar/Polar.ts, test/clip.html
Fix the bug that symbols will be unexpectedly clipped in some scenarios.
- #15292
- #16328
|  Before   | After |
|  :----:  | :----: |
| <img src="https://user-images.githubusercontent.com/26999792/148210620-0ed93113-661d-411b-b9b3-aee922840804.png" height="300"> | <img src="https://user-images.githubusercontent.com/26999792/148210960-2ec93174-3d6f-4b52-86b9-dea519757f95.png" height="300"> |
| <img src="https://user-images.githubusercontent.com/26999792/148211235-edb2cd45-dcb8-4de4-ba8d-8e386860fc35.png" height="300">  | <img src="https://user-images.githubusercontent.com/26999792/148211097-368dece4-db83-448e-9146-e1b79c548bcb.png" height="300"> |
| <img src="https://user-images.githubusercontent.com/26999792/148211305-906ed372-c75d-494c-b7f1-2bd2f656ad …
=> fix(polar): fix edge symbols are clipped unexpectedly for the tiny offset.

src/chart/pie/labelLayout.ts, test/pie-label-rotate.html
Fix pie label rotation when `startAngle` is set to values like 0.
- #15980
In some cases, the text rotation is up-side-down and hard to read.
All text is rotated upwards for better reading.
- test/pie-label-rotate.html
The `run` button changes `startAngle` and data to test it works in all situations.
=> fix(pie): tangential rotation with startAngle #15980

src/chart/treemap/TreemapSeries.ts, src/model/mixin/textStyle.ts, src/util/types.ts, test/bar3.html
Set width and overflow to textStyle so that text should set to be correct width when overflows.
#16189
Grid position was not correct because text width is calculated wrong.
Grid position calculated right.
test/bar3.html
=> fix(axis): axis label width when overflow is set

src/component/legend/LegendView.ts, test/pie-case.html
In the PR https://github.com/apache/echarts/pull/14497/files#diff-57be669601679875d9b233c7dc218568caae93a25cf1585ee5df4129dcfd82a2L248. The `style` object is modified unexpectedly if color is transparent. It will cause the chart can't be totally transparent. This PR cloned a new style to instead of modifying the original to fix this issue.
https://github.com/apache/echarts/issues/16064
N.A.
=> fix(visual): fix legend modify alpha on transparent color

src/model/Global.ts, test/tooltip-multiple.html
- Fix the bug that the page will be frozen if multiple tooltips are provided.
- Give a warning if it's in the development environment.
- #6722
- #9152
- #14850
- #16236
As the _**Multiple Tooltip**_ doesn't get supported yet, the page will get frozen if more than one tooltip is provided.
Check if there already exists a tooltip component and avoid creating another one to prevent the tooltip component from falling into an infinite loop that freezes the page.
Please refer to `test/tooltip-multiple.html`
=> fix(tooltip): fix the page will be frozen if multiple tooltips are provided.

src/component/radar/RadarView.ts, src/coord/radar/RadarModel.ts, src/preprocessor/helper/compatStyle.ts, test/radar3.html
Radar indicator names were displayed in the tooltip as "-" when `indicator.name.show` is set to be false. 
- #15915
Radar indicator names were displayed in the tooltip as "-" when `indicator.name.show` is set to be false. 
Radar indicator name should be displayed in the tooltip.
NA.
=> fix(radar): name being - in tooltip when name.show is false #15915

src/chart/lines/linesLayout.ts
Tweak #16184. Use echarts log instead of zrender log.
N.A.
=> fix(lines): use echarts log instead of zrender log.

src/chart/graph/GraphView.ts, test/graph-case.html
https://github.com/apache/echarts/issues/16366
=> fix(graph): fix error when symbol is none.

src/core/echarts.ts
We use a flag to check if there are unexpected update during another update, which may cause chaos like infinite loop. But currently if there are exceptions during update, the flag will not be cleared and this check keeps fail in the following update. For example if error happens in the callback. 
This PR handles exceptions during update to avoid following setOption or resize fails.
https://github.com/apache/echarts/issues/15280
=> fix(core): avoid error in render breaks following update

src/scale/helper.ts
The interval will have rounding error when increase interval by multiplying 3. It may happen when `alignTicks` is set true.
=> fix(scale): fix rounding error when increase interval in align ticks calculation

src/util/format.ts
tooltip中time类型的字段默认使用的12小时制展示，容易产生困惑，应改成24小时制展示
time类型在tooltip中以12小时制展示，实际数据是：2018-10-23 23:40:00
修复后，time类型在tooltip中以24小时制展示
=> tooltip中time类型的字段默认使用的12小时制展示，容易产生困惑，改成24小时制展示

src/component/toolbox/feature/DataView.ts
(1) Fix a bug that the tooltip won't be hidden when the data view is open.
(2) use 5px padding instead of inset 5px to avoid clicking the below layers.
- #15542
The tooltip wasn't hidden after the data view was open.
Hide the tooltip after the data view is open.
Please refer to `test/toolbox-tooltip.html`
=> fix(dataview): hide tooltip when data view is open.

src/component/graphic/GraphicView.ts, test/graphic-cases.html
Fix the bug that `cursor` doesn't work in `graphic` component.
- #16511
Please refer to the last case in `test/graphic-cases.html`.
`Group` doesn't support `cursor`/`invisible`/`progressive` as they are only for a single element. We should remove these options from our documentation.
=> fix(graphic): fix `cursor` doesn't work in `graphic` component.

src/chart/helper/EffectLine.ts, src/chart/helper/Symbol.ts, src/chart/helper/SymbolDraw.ts, src/chart/tree/TreeView.ts, test/lib/testHelper.js, test/node/ssr.js
- [] others
Reproduce demo of memory leak demo: https://uzedc5.csb.app/map-random.html
When we using setOption with notMerge. The model will be recreated but view will be reused. And the graphic elements in the view are also reused so we can apply transition animations easily.
In this case memory leaks happens in https://github.com/apache/echarts/blob/e4bdd30ea1a751fdb583367ff29fa122ba27be7d/src/chart/helper/EffectLine.ts#L162. The looped animation of graphic elements will be keeped when updating. It also keeps the closure of during callback. Which includes the old `lineData`:
I still can't figure out why this `lineData` will be kept in the closure because there is no code using it in the during callback.  Current workaroud is move the code of updating …
=> perf(lines): fix potential memory leak in the effect line when setOption with notMerge

src/chart/line/LineView.ts, test/line-step.html
fix that connectNulls with stepLine fails when after a long number of null entries occur
[#16424](https://github.com/apache/echarts/issues/16424)
option:
```
option={
title: {
text: 'Step Line',
},
tooltip: {
trigger: 'axis',
},
legend: {
data: ['Step Start', 'Step Middle', 'Step End'],
},
grid: {
left: '3%',
right: '4%',
bottom: '3%',
containLabel: true,
},
toolbox: {
feature: {
saveAsImage: {},
},
},
xAxis: {
type: 'category',
data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
},
yAxis: {
type: 'value',
},
series: [
{
name: 'Step Start',
type: 'line',
step: 'start',
connectNulls: true,
data: [120, 132, 101, 134, 90, 230, 210],
},
{
name: 'Step Middle',
type: 'line',
step: 'middle',
connectNulls: true,
data: [220, 282, null, 234, null, 430, …
```
=> fix(line): 过滤空节点, 避免阶梯线条变为斜线

src/visual/VisualMapping.ts
if `zrColor.parse` returns `undefiend`, use `#000` as default color
- Close #16574
N.A.
=> fix(sanky):fallback to black if color were illegal

build/source-release/prepareReleaseMaterials.js, build/source-release/template/vote-result.tpl
Add release vote result email template in release materials.
=> chore: add vote result template in the release materials

src/chart/tree/TreeSeries.ts
Add `isExpand` to `tree` click event callback
- Close #16650
N.A.
=> feat(event-tree): add `collapsed` to `tree` click event parameters

src/component/marker/MarkerView.ts, src/util/states.ts, src/view/Component.ts, test/markPoint.html
Set component's blur state to true when compoonent is blured
- Close #16665 
N.A.
=> fix(marker): marker state not restore after blur

src/component/visualMap/ContinuousView.ts, src/component/visualMap/PiecewiseView.ts, src/model/mixin/textStyle.ts, test/visualMap-continuous.html, test/visualMap-pieces.html
Fix a bug that some text styles are not working on `visualMap`. 
- #14440
| ![image](https://user-images.githubusercontent.com/29879262/158140242-0c221fe8-76e8-4721-8f89-40cfb78613fb.png) | ![image](https://user-images.githubusercontent.com/29879262/158140288-bac8e527-9ed0-488b-8480-d0f46e18e6bd.png) |
| ![image](https://user-images.githubusercontent.com/29879262/158140853-da2e459e-223d-411b-9924-f723201b8e0f.png) | ![image](https://user-images.githubusercontent.com/29879262/158140778-816f4619-26de-404a-857c-e8598fa47ac2.png) |
- `test/visualMap-continuous.html`
- `test/visualMap-pieces.html`
=> fix(visualmap): add textShadowColor, make text shadow work on visualMap. close #14440

src/chart/effectScatter/EffectScatterSeries.ts, src/chart/helper/Symbol.ts, src/chart/helper/SymbolDraw.ts, test/scatter.html
`scatter` `scale` support number
- Close #10033
N.A.
=> feat(scatter): `scale` support number

src/component/toolbox/feature/DataView.ts
Optimize the default textview style to fix unexpected scrollbar and outline.
| <img width="400" alt="mac" src="https://user-images.githubusercontent.com/26999792/158779494-6a7182e0-e747-4061-83f3-b7d3f4ef0f9b.png"> | <img width="400"  alt="mac" src="https://user-images.githubusercontent.com/26999792/158779509-28f31d8f-7c84-4627-a726-b720334be728.png"> |
| <img width="400" alt="windows" src="https://user-images.githubusercontent.com/26999792/158780002-0a7471e3-6775-4e0b-8fd6-4dedd9504ca5.png"> | <img width="400" alt="windows" src="https://user-images.githubusercontent.com/26999792/158779674-fb513d60-62b7-4d49-81f3-5d82d7d61f90.png"> |
Please refer to `test/dataZoom-toolbox.html`
=> fix(dataview): fix unexpected scrollbar and outline when using default textview

src/component/toolbox/ToolboxView.ts
Fix toolbox doesn't enter emphasis state when hovering on the icon.
- #13777
Please refer to #13777 for details.
Any test cases that enable the toolbox.
=> fix(toolbox): toolbox doesn't enter emphasis state when hovering on the icon.

src/chart/gauge/GaugeView.ts, test/gauge-case.html
1. Fix progress bar may become unexpectedly circle when value is `0` and `progress.roundCap` is enabled.
2. Fix ticks don't follow the axis direction when the chart is anticlockwise.
- #16640
Please refer to `test/gauge-case.html`.
=> fix(gauge): fix progress bar may become unexpectedly circle when value is `0` and `progress.roundCap` is enabled.

src/chart/heatmap/HeatmapView.ts, test/heatmap-gap-bug.html, test/heatmap-large.html, test/runTest/actions/__meta__.json, test/runTest/actions/heatmap-gap-bug.json
Fix some gaps will occur in the heatmap when dpr is not an integer.
- #6011
- #12519
- #11975
There are unexpected obvious gaps when dpr is not an integer.
Add extra 0.5px for each cell.
| ![image](https://user-images.githubusercontent.com/26999792/159249225-07242875-db03-4ccb-b1fb-c1f4a67cb453.png) | ![image](https://user-images.githubusercontent.com/26999792/159249211-253daafe-51b0-43c7-a5f4-235080af29c3.png) |
| ![image](https://user-images.githubusercontent.com/26999792/159250220-5e285041-4c4a-4b81-be08-552e02cf2117.png) | ![image](https://user-images.githubusercontent.com/26999792/159250320-fcd4c11c-9c72-4b5e-9d04-02b1967cffde.png) |
- `test/heatmap-gap-bug.html`
- `test/heatmap-large.html`
=> fix(heatmap): avoid the unexpected gaps when dpr is not an integer

src/data/DataStore.ts, test/dataZoom-feature.html
Fix the `dataZoom` was unexpectedly displayed at the top when data contains null values. Fixes #16476.
- #16476
Refer to the last case in `test/dataZoom-feature.html`.
=> fix(dataZoom): fix the dataZoom was unexpectedly displayed at the top when data contains null values

src/chart/line/LineSeries.ts, src/chart/line/helper.ts, test/area-origin.html
Allow `series-line.areaStyle.origin` to take number as input 
* Close #16717 
The choices for series-line.areaStyle.origin for now is limited to 'start', 'end', and 'auto', which correspond to baseline at bottom, top or axis of the view.
* origin: 'start'
* origin: 'end'
* origin: 'auto'
* And now what is required is to let origin accept a number and set the baseline right at the specified level. Take the picture below as an exmaple.
* What is changed in code?
* Here a second `else if` is added to take number in and set it to `valueStart`. NaN is excluded from such situation and will be treated as undefined.
```js
function getValueStart(valueAxis, valueOrigin) {
var valueStart = 0;
var extent = valueAxis.scale.getExtent();
if (valueOrigin === 'start') …
```
=> feat: allow areaStyle.origin to take number as input

src/component/axis/RadiusAxisView.ts, test/runTest/actions/__meta__.json, test/runTest/actions/splitLine.json, test/splitLine.html
The chart throws errors when `splitLine` is enabled in the radius axis, resolves #16731.
- #16731
It will throw illegal argument errors as zrender basic shape `Circle` doesn't handle the value less than `0`, unlike the `Sector` shape, it normalizes such an unexpected radius value.
Ensure the circle radius is non-negative in ECharts.
Please refer to `test/splitLine.html`
=> fix(splitLine): fix chart throws errors when `splitLine` is enabled in radius axis.

src/component/toolbox/ToolboxView.ts, test/toolbox-title.html
Fix the toolbox title may be outside of the chart. This PR relies on #16702.
- https://github.com/apache/echarts/issues/16673#issuecomment-1068775607
- #16472
- #14833
Toolbox title may be outside of the chart so that it can't be fully displayed.
| 1 | 2 |
| ![bug1](https://user-images.githubusercontent.com/26999792/159122929-fcac6b02-7f6e-4426-97b0-83efcc6b2ebe.png) | ![bug2](https://user-images.githubusercontent.com/26999792/159122933-65ca13b9-567d-40bd-ab49-9c6ae2e5c7c8.png) |
| 1 | 2 | 3 |
| :----: | :----: | :----: |
| ![h-tl](https://user-images.githubusercontent.com/26999792/159123009-ddfffcbc-6fc4-4f3c-b8b0-fa9ffeb96b9d.png) | ![h-tl1](https://user-images.githubusercontent.com/26999792/159123010-d4c5a346-4120-462b-b896-00a7bb …
=> fix(toolbox): fix toolbox title may be outside of the chart

src/component/toolbox/feature/SaveAsImage.ts, src/core/echarts.ts
Change the expected image types from `jpg` to `jpeg`.
=> fix: wrong jpg instead of jpeg image export types

.asf.yaml
This will reset your notifications back to commits@infra for PRs and issues.
=> [infra] reset notifications to commits@echarts for commits, PRs and issues

src/component/dataZoom/SliderZoomView.ts
- Close https://github.com/apache/echarts/issues/16849
https://github.com/apache/echarts/issues/16849
dataZoom.borderColor not work
dataZoom.borderColor work
N.A.
=> fix: bug 16849

src/chart/graph/GraphSeries.ts, src/chart/graph/GraphView.ts, src/chart/helper/Symbol.ts, test/graph-symbol.html
=> fix(graph): user cursor has higher priority

.github/workflows/ci.yml
Fix node modules cache doesn't work for missing the step id and the wrong cache target directory.
See https://github.com/apache/echarts/actions/runs/2162264848
=> ci: fix node modules cache doesn't work

src/component/legend/LegendView.ts, src/model/mixin/itemStyle.ts
Fix the problem that the legend patterns are still with decals when user sets 'legend.itemStyle.decal' to 'none'.
- fix #16909
As is described in https://github.com/apache/echarts/issues/16909#issuecomment-1104676217, `legend.itemStyle.decal` is directly overwritten by series itemStyle without checking if it's set to 'none' by user.
By adding the 'decal' into the ITEM_STYLE_KEY_MAP, Echarts now can correctly read the value of `legend.itemstyle.decal` set by users.
By checking whether user sets `legend.itemstyle.decal` to `none`, we decide whether `decal` should be overwritten by series itemStyle.
N.A.
=> fix: legend visual still with decal when user set 'legend.itemStyle.decal' to 'none'

src/chart/helper/EffectLine.ts, src/chart/helper/EffectPolyline.ts, src/chart/helper/LineDraw.ts
add the effect.goback property in series-lines to enable the effect animation can go back to the starting point after reaching the destination. it`s necessary to indicates a round trip flight.
the effect animation in series-lines is one-way, can not indicates a round trip flight.
add the effect.goback property in series-lines to enable the effect animation can go back
N.A.
=> feat(LineDraw):series-lines support the effect animation go back

src/component/tooltip/TooltipView.ts
Fix the problem that the tooltip changes as the axis extent changes when `triggerOn` is set to `click`
- fix #16930
When `tooltip.triggerOn` is set to `'click'`, tooltip is expected to stay the same until user clicks another item. But the tool tip content will change with axis extent now after zooming in and slide the axis around. The reason causing this is stated in https://github.com/apache/echarts/issues/16930#issuecomment-1107786045
The content of tooltip will stay the same until user clicks another item.
N.A.
=> fix: tooltip content changes with axis extent when 'triggerOn' set to 'click'

.github/ISSUE_TEMPLATE/bug_report.yml
Fix broken JSFiddle link and CodeSandbox link
=> chore: fix broken external editor links

src/action/roamHelper.ts, src/chart/graph/createView.ts, src/chart/graph/install.ts, src/chart/tree/TreeView.ts, src/chart/tree/treeAction.ts, src/component/geo/install.ts, src/coord/View.ts, src/coord/geo/Geo.ts, src/coord/geo/geoCreator.ts, src/util/types.ts, test/graph-simple.html, test/tree-legend.html
`View` center option support `string`
- Close #14764
N.A.
=> feat(View): `View` center supports `string`

src/chart/tree/TreeSeries.ts, src/chart/tree/TreeView.ts, test/tree-legend.html
We had `ancestor` and `descendant`, but user might want to see the full relation with it's relative.
test/tree-legend.html
=> feat(tree): `tree` focus supports `relative`

src/processor/dataStack.ts, src/util/types.ts, test/area-stack.html
This PR adds a new property `stackStrategy` to the `SeriesStackOptionMixin` which defaults to `samesign` (current behavior). Associated PR on the docs repo: https://github.com/apache/echarts-doc/pull/255
- Closes #9317
- Close #9141
- Close #13747    
- Close #15083     
- Close #14365
Currently stacking is only applied if the cumulative sum has the same sign as the value to be stacked. This makes it impossible to mix positive and negative values in the same series, something typically needed when creating confidence bands:
Here we introduce the following new stacking options:
- `all`: stack all values, irrespective of the sign of the stackable value:
- `positive`: only stack positive values:
- `negative`: only stack negative values:
We also add the …
=> feat: add new stacking strategies

src/coord/geo/Geo.ts, test/linesGL-ny-appendData.html
Fix `dataToPoint` may not be working in `lineGL` series - add back two missing arguments to `projectedToPoint` called in Geo `dataToPoint` function.
- #16967
The example `lineGL-ny` can't work since v5.3.0 - All lines collapse to the left top corner.
Add back two missing arguments to `projectedToPoint` called in Geo `dataToPoint` function.
Please refer to `test/linesGL-ny-appendData.html`
Related PR: #16364
=> fix(geo): fix `dataToPoint` may not be working in lineGL series.

src/chart/bar/PictorialBarSeries.ts
Let the interface **PictorialBarSeriesOption** extends the interface **SeriesEncodeOptionMixin** .
No issues.
The interface **PictorialBarSeriesOption** don't extends interface **SeriesEncodeOptionMixin**.
But **PictorialBar** supports the config `encode`  as document describled.
So,this PR was produced to improve the definition of **PictorialBar**.
Let the interface **PictorialBarSeriesOption**  extends interface **SeriesEncodeOptionMixin** .
N.A.
=> fix:improve PictorialBarSeriesOption

.github/pull_request_template.md
Improve the PR template so that doc can always under control for each issue.
The release manager has to manually look through all pull requests in a certain release to check whether there should be document changes and whether they have been made into the `echarts-doc` repo. Sometimes it's hard for the release manager to know the detail of all PRs so it's not always an easy job to do.
So I decide to improve the workflow so that:
- The author of a PR is mainly responsible to decide whether a PR requires document changes and whether a PR in `echarts-doc` repo has been made. This is done by editing the description of the PR.
- The reviews of the PR should check this info before merging.
The [Apache ECharts bot](https://github.com/apps/echarts-bot) is …
=> chore: update pr template to improve doc control

src/chart/sunburst/SunburstSeries.ts, src/chart/treemap/TreemapSeries.ts
Fix interface **SunburstSeriesOption** and **TreemapSeriesOption** .
No issue.
**Sunburst** and **Treemap** supports the option `nodeClick=false` as document described.
But,the interface SunburstSeriesOption and TreemapSeriesOption is inaccurate.
Add the `false` to the interface SunburstSeriesOption.nodeClick and TreemapSeriesOption.nodeClick.
N.A.
=> fix(types): fix `SunburstSeriesOption` and `TreemapSeriesOption` types

src/chart/treemap/Breadcrumb.ts, src/chart/treemap/TreemapSeries.ts, src/data/DataStore.ts, src/data/Graph.ts, src/data/Tree.ts, src/model/Global.ts, src/visual/VisualMapping.ts, test/treemap-simple.html
Add `emphasis` state to `breadcrumb`
- Close #15741 
test/treemap-simple.html
=> feat(treemap.breadcrumb): add `emphasis` state

.github/workflows/stale.yml
Follow up with the latest GitHub updates, close stale issues as **_not planned_**.
=> chore(workflow): close stale issues as not planned rather than completed

.github/workflows/stale.yml
fix `close-issue-reason` option is not being recognized. It's introduced in v5.
Related PR: #17304
=> chore(workflow): upgrade stale action to v5

src/component/axis/AxisBuilder.ts, test/axis-arrow.html
Fix the symbol of the axis line is not reversed when the axis is reversed.
- Resolves #17325
| <img src="https://user-images.githubusercontent.com/26999792/177685065-c24ae05e-2028-49a4-9d15-0625e1393300.png" width="400"> | <img src="https://user-images.githubusercontent.com/26999792/177685088-be1e12c3-727a-4f46-9d63-b81dc1f8681c.png" width="400"> |
Please refer to `test/axis-arrow.html`
=> fix(axis): fix axis symbol is not reversed when axis is reversed

src/action/roamHelper.ts, src/chart/graph/GraphSeries.ts, src/chart/graph/install.ts, src/chart/line/LineSeries.ts, src/chart/scatter/ScatterSeries.ts, src/chart/tree/treeAction.ts, src/component/geo/install.ts
PR #16688 allows customizing the scale size of the symbol, but it is only for the EffectScatter series. In fact, this new feature is suitable for the symbol of all series. So this PR is to add the missing type to the Scatter, Line, and Graph series.
- Resolves  https://github.com/apache/echarts/issues/17072#issuecomment-1173256689
- Resolves #17384
N.A.
=> fix(type): add missing type `number` to `emphasis.scale` for scatter/line/graph series

package-lock.json, package.json, src/util/format.ts
Fix the generated SVG string may be broken if it contains special HTML characters. See also ecomfe/zrender#935.
- Resolves #17399 
test/visualMap-pieces.html
=> fix(svg): encode HTML special characters when generating SVG string

src/coord/single/Single.ts, src/coord/single/SingleAxis.ts
修复单轴反向的bug，原来属性定义的是inverse，在使用的时候是reverse
N.A.
=> fix(axis): fix `inverse` option does not work for `singleAxis`

src/component/marker/MarkAreaView.ts, src/component/marker/MarkLineView.ts, src/component/marker/MarkPointView.ts, src/component/marker/markerHelper.ts
fix word spelling mistakes
N.A.
=> style: spelling mistakes

src/chart/custom/CustomView.ts
This PR fixes an error brought by #17349.
If custom `renderItem` returns null in the first `setOption`, then in the next `setOption` if it's set to be null, `oldChild` is null so `oldChild.ignore = true;` will bring an error. `null/undefined/{}` is not supported because group element should not be null.
N.A.
=> fix(custom): set ignore only if old child exists

src/animation/customGraphicKeyframeAnimation.ts, src/chart/custom/CustomView.ts, src/coord/geo/geoCreator.ts
- Fix incorrect import of `SeriesModel` from `echarts.all`. See also
https://github.com/apache/echarts/pull/17349#discussion_r932843099
- Fix similar issues in `geoCreator.ts` & `animation/customGraphicKeyframeAnimation.ts`
=> chore: fix wrong imports from `echarts.all`

src/chart/pie/PieSeries.ts, src/util/number.ts, test/pie-percent.html, test/pie3.html
饼图现在的渲染有性能问题，getPercentWithPrecision是很消耗性能的方法，每一个数据项都需要执行一次，在10000个数据点的时候就能把页面卡死，可以总的执行一次再取数使用。
#17173 
N.A.
没有删掉getPercentWithPrecision，因为api里面有暴露给外包
测试之前需要执行 prepublish
=> perf(pie): optimize performance of pie series

theme/infographic.js, theme/macarons.js, theme/macarons2.js, theme/shine.js, theme/tech-blue.js, theme/tool/option/area.js, theme/tool/option/bar.js, theme/tool/option/graph.js, theme/tool/option/map.js, theme/tool/option/pie.js
=> fix(theme): fix the abandoned normal level in the theme file

src/chart/gauge/GaugeSeries.ts, src/chart/gauge/GaugeView.ts, test/gauge-case.html, test/gauge-simple.html
gauge text label rotate.  https://github.com/apache/echarts/issues/15944
gauge text label can`t rotating by angle.
add new option: `gauge-series.axisLabel.rotating`
if true, rotating label by angle.
gauge-case.html
gauge-simple.html
=> feat(gauge): axisLabel support angle rotating. close 15944

src/component/dataZoom/SliderZoomView.ts
Fix the error that occurs when using `sliderZoom` component in candlestick with dataset.
- #17228
As is illustrated in #17228, error occurs when using `sliderZoom` component in candlestick with dataset.
No errors occur now. The pr has passed the visual tests too.
N.A.
=> fix: sliderZoom in candlestick dataset error

src/scale/Interval.ts, src/scale/Log.ts, test/logScale.html
When the log axis contains only one data and its value is less than 1, echarts fail to render. This PR fixes this problem.
#13154
```js
chart.setOption({
xAxis: {
type: 'value',
},
yAxis: {
type: 'log',
logBase: 2,
},
series: [
{
type: 'scatter',
itemStyle: {
color: 'red',
},
data: [
[1, .5],
],
},
],
});
```
N.A.
=> fix(log): fix log axis breaks a single data whose log value is negative

extension-src/bmap/BMapCoordSys.ts, src/chart/pie/pieLayout.ts, test/pie-coordinate-system.html
1. Add coordinate system support for pie series.
2. BMap extension supports `convertToPixel` & `convertFromPixel` API.
- #13851
- plainheart/echarts-extension-amap#38
It's not convenient and not direct to display the pie series on Geo/BMap/AMap/Calendar coordinate system.
Add a new option `coordinateSystem` for pie series.
Please refer to `test/pie-coordinate-system.html`
=> feat(pie): support specifying coordinate system for pie series.

theme/macarons.js
fix tooltips text style of the theme macarons same as v4.9.0
* [5.3.3部分配置项默认值同文档不一致](https://github.com/apache/echarts/issues/17542)
The theme macarons' tooltips style is not sam as it show in v4.9.0
The theme macarons' tooltips style is same as the tooltips show in v4.9.0
N.A.
=> fix(theme): fix tooltips text style of the theme macarons

src/animation/basicTransition.ts, src/chart/bar/BaseBarSeries.ts
Allows using echarts with newly released ts@4.8, when .d.ts are being checked.
fixes #17581
See #17581
Passes type checking
N.A.
=> fix: ensure compatibility with typescript@4.8

.eslintrc-common.yaml, src/coord/axisHelper.ts, src/core/task.ts, src/export/api.ts, src/layout/barPolar.ts, src/util/states.ts, src/util/types.ts
Disallow comments starting without space. For example: `//This is not allowed`.
Sometimes contributors forget to add a space after comment starts.
The CI will break if there is no space after a comment starts.
N.A.
=> chore(lint): enforce consistent spacing after comment starts

extension-src/bmap/BMapModel.ts, extension-src/bmap/README.md
To improve documentation of the bmap extension.
N.A.
N.A.
=> docs(extension/bmap): improve documentation of bmap extension

src/chart/gauge/GaugeView.ts, test/gauge-case.html
add gauge sectors in the order of the "clockwise" option
#17633 
The gauge view adds sectors in the order of the `colorList` option,  however, these elements will be covered by elements added later, and the order of the sectors looks reversed when the `roundCap` option is enabled.
Reverse the sectors array before adding them to the graphic group
[gauge-case](https://github.com/ZeekoZhu/echarts/blob/86bbd4d8dd0b828cd91aa45584df53808d41e0db/test/gauge-case.html)
=> fix #17633: add gauge sectors in the order of the "clockwise" option

src/chart/pie/labelLayout.ts, test/pie-label.html
Fix an undefined error of `labelLine` when the sector angle is less than `minShowLabelRadian`.
This bug was unexpectedly brought by #17412, which is in v5.4.0.
- Resolves #17712
Please refer to the last case in `test/pie-label.html`
=> fix(pie): fix `labelLine` NPE when `minShowLabelRadian` is set

src/core/echarts.ts
fix type error about `height` and `width` of `EChartsInitOpts`
#17667 
[Bug] The documentation for EChartsInitOpts has a type error about height and width
The description type of the document differs from that in the code
Add union types `number | string` for `height` and `width` 
N.A.
=> fix: EChartsInitOpts type error about height and width. close #17667

.github/workflows/ci.yml, .github/workflows/nightly-next.yml, .github/workflows/nightly.yml, .github/workflows/source-release.yml, .github/workflows/stale.yml
1. Update deprecated Node v12 to v16 for removing the warnings from GitHub Action.
See also https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
2. Update the dependency actions to the latest version.
=> chore: update deprecated Node v12 to v16 & update action dependency version

src/animation/universalTransition.ts, test/universalTransition2.html
dataGroupId for old data items in universalTransition is mistakenly set to that of new data items, not the expected old one. So fix it.
- #17309
https://github.com/apache/echarts/blob/89d57f21b7eabfcc6770447f6cf6a20a8f406585/src/animation/universalTransition.ts#L210
When processing old data items, after executing this line, dataGroupId is wrongly assigned a value that is belong to new data items. That will cause universalTransition not work if we fall back to depend on dataGroupId to decide dataItem's key.
By storing the old dataGroupId in globalStore, now the correct old dataGroupId can be accessed!
I think [the example](https://echarts.apache.org/examples/zh/editor.html?c=bar-drilldown) should be updated with …
=> fix: incorrect dataGroupId for old data items in universalTransition

src/animation/customGraphicTransition.ts, src/component/dataZoom/roams.ts, src/component/helper/MapDraw.ts, src/coord/View.ts, src/coord/axisHelper.ts, src/coord/geo/GeoSVGResource.ts, src/coord/geo/Region.ts, src/core/Scheduler.ts, src/data/DataStore.ts, src/data/helper/SeriesDataSchema.ts, src/data/helper/transform.ts, src/export/charts.ts, src/layout/barGrid.ts, src/model/Component.ts, src/model/Global.ts, src/model/Model.ts, src/model/OptionManager.ts, src/model/Series.ts, src/model/mixin/dataFormat.ts, src/util/types.ts, src/view/Chart.ts, src/view/Component.ts
Fixes a few typos in the code (inside comments).
This PR fixes a few typos.
N.A.
=> chore: fix some typos

src/chart/candlestick/CandlestickSeries.ts, src/chart/candlestick/CandlestickView.ts, src/chart/candlestick/candlestickLayout.ts, src/chart/candlestick/candlestickVisual.ts, test/candlestick-doji.html
Provide option `series-candlestick.itemStyle.borderColorDoji` to set custom doji color.
#11042
Doji means the open and close value of a data item is the same. Previously, it can either be `borderColor` or `borderColor0` according to the previous data item. But if developers want to change it to a custom color, like a neutral colour like gary, it cannot be done.
So in this PR, we provide a new option `borderColorDoji`. If it is set, this color is used for all doji data items.
`test/candlestick-doji.html`
=> feat(candlestick): provide borderColorDoji option for custom doji color

src/core/CoordinateSystem.ts, src/core/Scheduler.ts, src/core/echarts.ts, src/core/impl.ts, src/core/task.ts, src/export/api.ts, src/export/api/helper.ts, src/model/Component.ts, src/model/Global.ts, src/model/OptionManager.ts, src/model/Series.ts, src/model/internalComponentCreator.ts, src/scale/Interval.ts, src/scale/Time.ts, src/visual/VisualMapping.ts, src/visual/aria.ts, src/visual/helper.ts
Fixes some typos in the code.
This PR fixes a few typos.
N.A.
=> chore: fix a few typos

.github/workflows/nightly-next.yml, .github/workflows/nightly.yml, build/nightly/post.js, build/nightly/prepare.js
To make the changes available in time, always install the latest nightly version of zrender when publishing nightly echarts.
=> chore(workflow): always install the latest nightly version of zrender when publishing nightly echarts

src/chart/graph/GraphView.ts
PR #15428 enable draggable for all layout(could test in `test/graph-draggable.html`), but #16867 maybe override the flag unintentionally resulting that draggable only work on `layout: force`.
This pr fix it.
N.A.
=> fix(graph): draggable only work on force layout

src/coord/axisCommonTypes.ts
Co-authored-by: Giulio Mazzanti <gmazzanti@protonmail.com>
~~This PR sets the correct interface that AxisLabelBaseOption extends, changing it from TextCommonOption to LabelOption.~~
This PR adds the overflow property to the AxisLabelBaseOption interface.
- #17363 : ...
The overflow property on xAxis.axisLabel works fine as you can see from this demo: [Chart demo](https://echarts.apache.org/examples/en/editor.html?c=line-simple&lang=ts&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOQDKYOIsAMhNDpUQL4A0RYwwWSCAKpiGAE4QA5lJziqAQ1IQAzu3TciuWdAAmIoul0KwCggG0adBrQXiwlLrCv1YAWQi7duR89quAUT1KAF1OHnQpSX1CMVwAMwpnAGYAUkdDWEkpAAskygAWdIjiACNgMD4AWyo0jLEAYxhTFkYFUpwsAjBxAFcccN5-LHLSAzF4nBNe8XxYsVgVBQA3HABBFQBJKoVZEQ5Mg40S0jXlFXHiMABPEDnKBpMcKWBxa_riY1MLSjcYX0oABV-jhQW …
=> fix(type): add overflow property to AxisLabelBaseOption interface. close #17363

src/coord/Axis.ts, src/coord/CoordinateSystem.ts, src/coord/View.ts, src/coord/axisCommonTypes.ts, src/coord/axisDefault.ts, src/coord/axisHelper.ts, src/coord/axisTickLabelBuilder.ts, src/coord/cartesian/defaultAxisExtentFromData.ts, src/coord/geo/Geo.ts, src/coord/geo/GeoModel.ts, src/coord/geo/GeoSVGResource.ts, src/coord/geo/geoTypes.ts, src/coord/parallel/Parallel.ts, src/coord/parallel/ParallelModel.ts, src/coord/scaleRawExtentInfo.ts, src/layout/barGrid.ts, src/util/graphic.ts, src/util/symbol.ts, src/util/types.ts, src/visual/style.ts
This PR fixes a few typos.
N.A.
=> chore: fix various typos

package-lock.json, package.json, src/data/helper/createDimensions.ts
ecomfe/zrender#966 has refactored the HashMap, which prefers the native built-in `Map`. It causes the `HashMap.data.hasOwnProperty` to be not working. So this PR is to change it to `map.hasKey`.
Fix failed unit test `test/ut/spec/data/createDimensions.test.ts`
Failed information: https://github.com/apache/echarts/actions/runs/3368150373/jobs/5586364387
Please refer to `test/ut/spec/data/createDimensions.test.ts`
=> fix(data): change deprecated `map.data.hasOwnProperty` to `map.hasKey`

src/component/tooltip/TooltipHTMLContent.ts, test/runTest/actions/__meta__.json, test/runTest/actions/tooltip-domnode.json, test/tooltip-domnode.html
Fix a bug that the tooltip arrow may cover the content when its border is wide
N.A.
| ![image](https://user-images.githubusercontent.com/26999792/200171602-22e152cf-4101-4b12-81c3-c98b8d3c5345.png) | ![image](https://user-images.githubusercontent.com/26999792/200171508-bffac19c-188f-4197-99e5-db97f7c288ff.png) |
Please refer to the last case in `test/tooltip-domnode.html`
=> fix(tooltip): fix tooltip arrow may cover the content when border is wide

README.md, package.json
Start a local server when run `npm run dev` and update the README. Hopefully, this can better help new contributors to get started.
#17868
N.A.
=> chore: start a local server for testing when run dev #17868

src/chart/lines/LinesSeries.ts, src/chart/lines/LinesView.ts
- Add missing `function` callback into `lineStyle.color` for lines series.
- Remove unsupported `function` callback from `lineStyle.color` in states
- Resolves #17767
N.A.
=> fix(lines): add missing `function` callback into `lineStyle.color` for lines series.

src/chart/pie/PieSeries.ts
#17132 added support for setting the coordinate system of pie series but it didn't update the type of the `center` option.
This PR is to add the missing `number` & `string` type into the `center` option.
- #17132
N.A.
=> fix(type): add `string` & `number` type into the `center` option of pie series

src/chart/pie/pieLayout.ts, test/pie-coordinate-system.html
Fix a bug that exists in #17132 (v5.4.0)
Due to being normalized to an array, the `center` may not be converted to the correct point when the coordinate system is specified. For example, just like the LngLat array, `center: 'Beijing'` should also be converted to the correct pixel when using the `geo` coordinate system.
- #17132
Please refer to the 2nd and 7th `test/pie-coordinate-system.html`
=> fix(pie): fix `center` may not be converted to correct point when coordinate system is specified

src/component/dataZoom/AxisProxy.ts, test/axis-lastLabel.html
Fix the `dataZoom` can't render when `start/end/startValue/endValue` doesn't exist in the axis categories or is invalid value. 
N.A.
Fallback to extent start/end when parsed value or percent is invalid.
Please refer to the 4th case in `test/axis-lastLabel.html`
=> fix(dataZoom): fallback to extent start/end when parsed value or percent is invalid.

src/processor/dataStack.ts
Revert pr #17809 because #17801 is not a bug but not used correctly.
v5.3.3 introduced a new option [stackStrategy](https://echarts.apache.org/zh/option.html#series-bar.stackStrategy), and if a series should always stack from 0 rather than other series, it should be set to `'negative'` or `'positive'`. If not set, the default value is `'samesign'` and the data should be stacked on other series no matter the other part of the series is positive or negative.
PR #17809 makes the test case `axis-filter-extent2.html` fail and was found before new version release.
`axis-filter-extent2.html` fails.
`axis-filter-extent2.html` doesn't fail and developers should set `stackStrategy: 'negative'` in cases like #17801 or #17942. A working demo is …
=> fix(stack): revert pr #17809

src/core/echarts.ts
- fix: use `!=` to check if series is excluded as native map returns `undefined` rather than `null`
- chore: use hasGlobalWindow constant from env util
- chore: use warn util instead of `console.warn`
Please refer to `test/area-stack.html`
=> fix(core): use `!=` to check if series is excluded as native map returns `undefined` rather than `null`

package-lock.json, package.json
fix terser 5.3.8 regular expression leads to ReDoS
there had one pull request [#17407](https://github.com/apache/echarts/pull/17407) ,but only modifed package-lock.json 
N.A.
=> chore(deps-dev): bump terser from 5.3.8 to 5.16.1

src/chart/tree/TreeSeries.ts
Fix typescript error when providing a callback to the `symbol` property of the tree series.
When providing a callback to the `symbol` property of the tree series, the following typescript error appeared:
Callback function itself was working, but type definition was wrong.
This was happening because `TreeSeriesOption` extended `SymbolOptionMixin` instead of `SymbolOptionMixin<CallbackDataParams>` interface.
Now it is possible to provide a callback to the tree series `symbol` without typescript errors.
N.A.
=> fix(tree): change symbol type. close #17946

src/chart/line/LineView.ts, test/runTest/actions/__meta__.json, test/runTest/actions/svg-ssr.json, test/svg-ssr.html
1. Fix label doesn't show and line path doesn't update correctly in the `line` series when `ssr` is enabled.
2. Fix a typo: `seriesDalay` -> `seriesDelay`
- #18027
| ![image](https://user-images.githubusercontent.com/26999792/206118064-8179d9bc-18cb-4221-b749-f29ddc9646d5.png) | ![image](https://user-images.githubusercontent.com/26999792/206118137-42c4a691-85c8-421f-94a5-09291e448a08.png) |
| ![image](https://user-images.githubusercontent.com/26999792/206118254-bd03fbf6-05dc-4a34-b88e-02a78a2b76b0.png) | ![image](https://user-images.githubusercontent.com/26999792/206118296-f7273964-3715-4be2-bf72-38b2f9a63f6e.png) |
N.A.
=> fix(ssr): fix label doesn't show in line series when `ssr` is enabled

src/data/DataStore.ts, src/data/Graph.ts, src/legacy/dataSelectAction.ts, src/model/Series.ts
=> fix few typos

src/data/Source.ts, test/dataset-category.html
Replace `each` by `keys` to retrive correct dimension from object source.
- close #18050
`test/dataset-category.html`
=> fix(dataset): object source contains `length` breaks render

src/chart/sunburst/SunburstPiece.ts, test/sunburst-label.html
`sunbrust` label might upside down under `radial` rotation
- Close #18023 
`sunburst-label.html`
=> fix(sunburst): `radial` rotation label might upside down

src/chart/sunburst/SunburstSeries.ts, src/util/types.ts
- fix `treePathInfo` is missing in the type of formatter callback
- add missing type definition for the `data` option
- #18308
```ts
const option: echarts.EChartsOption = {
series: [{
type: 'sunburst',
levels: [
{
label: {
formatter(p) {
const { treePathInfo } = params
return ''
}
}
}
],
label: {
formatter(params) {
const { treePathInfo } = params
return ''
}
},
data: [
{
label: {
formatter(params) {
const { treePathInfo } = params
return ''
}
}
}
]
}]
};
```
=> fix(type): fix `treePathInfo` is missing in the type of sunburst formatter callback

src/chart/bar/BaseBarSeries.ts, src/component/marker/markerHelper.ts, test/bar-markArea.html, test/marker-case.html
Fix the markArea range problem in bar series.
#18130 and #18099
The markArea range is wrong in bar series when the axisTick is not all displayed. This was a bug introduced in #17098.
`tickValue` is the index in the total axis range, rather than the visible part. After the fixing, it works well when axis has interval or with dataZoom.
`bar-markArea.html`
=> fix(markArea): markArea range in bar series #18130

src/chart/sankey/SankeyView.ts, src/label/labelStyle.ts, test/sankey-labelValue.html
fix: The Label Value of Sankey Chart is always an undefined problem.
【中文】解决：桑基图Label Value总是undefined的问题。
- #18212 
Bug 请看下图：
修复之后效果如下：
N.A.
=> 修复：Sankey桑基图Label Value总是undefined的问题。

package.json
Update deprecated npm `prepublish` hook in favor of  `prepare`. See also ecomfe/zrender#998.
=> chore: update deprecated npm `prepublish` hook to `prepare`

src/chart/parallel/ParallelSeries.ts
Fixed datatype of Typescript in echarts/src/chart/parallel/ParallelSeries.ts file for 
value? : ParallelSeriesDataValue[] 
to
value?: ParallelSeriesDataValue
#18411 
The issue is fixed as discuss in dscussion
The typescript compiler shows an error when creating a ParallelSeriesOption
The typescript compiler will not show error when creating a ParallelSeriesOption
N.A.
=> fix(type): fix wrong type for data item value of the `parallel` series.

.github/ISSUE_TEMPLATE/bug_report.yml
What Ovilia feels matters.
Too many people are submitting low cost invalid issues.
Reproduction link is required for new issues. (And proper explanation for that of course)
N.A.
=> chore: make reproduction link required

.github/ISSUE_TEMPLATE/bug_report.yml
Mostly, it's enough to make simple reproduction with the official editor.
=> chore: add official editor link to issue template

src/component/legend/LegendView.ts, test/legend-style.html
Inherit the legend's rich text color from the legend's options.
- #18196
Rich text within the legend was inheriting color from the theme instead of the colors configured in the legend.
The rich text within a legend is inheriting now the colors from the legend's configuration (`legend.textStyle.color` when the legend item is active and `legend.inactiveColor` when inactive). However, user is still able to set color in rich options which will override `legend.textStyle.color`.
The problem was fixed by specifying `inheritColor` option in `createTextStyle` function.
N.A.
=> fix(legend): inherit legend rich text color from legend's options

src/util/time.ts, test/ut/spec/util/time.test.ts
fix time format for `{yy}`
- https://github.com/apache/echarts/issues/18534
time format not pad for {yy}
'2003' -> '3'
time format pad for {yy}
'2003' -> '03'
add new ut test for time format
`test/ut/spec/util/time.test.ts`
=> fix(time-format): fix yy time format

src/label/labelStyle.ts, src/util/types.ts, test/label-ellipsis.html
`ellipsis` was not working for all options but the document has this option.
#18517
`ellipsis` was always `'...'`.
`ellipsis` can be changed.
N.A.
=> fix(label): ellipsis was not working

.github/workflows/ci.yml, .github/workflows/nightly-next.yml, .github/workflows/nightly.yml, .github/workflows/source-release.yml, package-lock.json, package.json
The unit test always [fails](https://github.com/apache/echarts/actions/runs/4752590603/jobs/8444308558#step:4:286)  in node v18 due to the `jest-canvas-mock` dependency.
As per the release note, it has been fixed since [v2.4.0](https://github.com/hustcc/jest-canvas-mock/releases/tag/v2.4.0). See also hustcc/jest-canvas-mock#91
=> chore: update `jest-canvas-mock` to fix test fails in node v18

src/core/echarts.ts
update `init` function type signature so it can be identical to official document
According to the official document, we can pass `null` to the first or the second parameter. However, the type signature disallow pass `null`
https://echarts.apache.org/handbook/en/best-practices/canvas-vs-svg/
https://echarts.apache.org/handbook/en/how-to/cross-platform/server/#server-side-rendering
N.A.
=> fix(type): allow passing `null` to the parameters of `init` function

src/echarts.all.ts
This PR fixes a small typo in the chart options. Specifically, it changes "setOptionp" to "setOption" and "coodinate" to "coordinate". These changes improve the clarity and accuracy of the code.
N.A.
=> fix: typo in echarts.all.ts

src/coord/Axis.ts
Show last tick for single data
#18453
No last tick when data length is 1.
Has last tick when data length is 1.
- The first test case in `axis-extrema.html`
I've run visual tests for all cases and saw no problems.
=> fix(axis): show last tick for single data #18453

src/core/echarts.ts
Make `disconnect` no longer marked as deprecated.
N.A.
=> fix(api): only deprecate disConnect but not disconnect

.github/workflows/ci.yml
Generate a link for directly previewing the changes in ECharts example editor.
N.A.
=> chore: add PR preview workflow

.github/workflows/ci.yml
Fix the wrong environment variable `github.pull_request.merged` -> `github.event.pull_request.merged` in #18803.
=> chore(workflow): fix wrong env variable

src/chart/line/LineView.ts, test/line-endLabel.html
Check `setLabelText` exists before calling.
#18839
`endLabel` fail when data contain `null` or `'-'`.
`endLabel` not fail when data contain `null` or `'-'`.
N.A.
=> fix(endLabel): endLabel fail with null data #18839

src/core/echarts.ts
Fixed a typo in the file by changing "hasSeperateZLevel" to "hasSeparateZLevel".
=> chore: fix a typo in `core/echarts.ts`

src/util/graphic.ts
Add `| undefined` to return type of `graphic.clipRectByRect`.
`graphic.clipRectByRect` can return undefined, but this is not reflected in it's type signature.
`graphic.clipRectByRect` has `undefined` as a possible return type.
N.A.
=> fix(type): add `undefined` to the return type of `graphic.clipRectByRect` function

src/data/Source.ts, test/dataset-source-two-typed-array.html
fix source formate detect error when dataset's source is multi typed array.
- Fix #18963
|| [Before](https://echarts.apache.org/examples/zh/editor.html?c=line-simple&code=MYewdgzgLgBAJgQygiBTWBeGBtAUDGMVAdxgDEAbEJAZgCYBBAJyYQE8AKfAmAVQEswUABzNWbAHQAzJiAC2HJCABGHAOQMGAYQYAFYpoYBRQ0YBChnQEVDIE5oCyFhwC8HAEStWMGNQEoAGhgOYD8YDAA-bh4YYAlgAAsEJi0QOFQGKA4ABj9omD8JZQBXKSlUJm5A7mwARiC6IJoggBYggFYggDYggHYAXVx-gG5cXBAAByh-cHCYAG9uAA8GJf4IAC4F_Kg2CdQttQA3BApi1DUA_IgEkGItqCZz7gBfK4I2VfWtxZjd_cOJzOF3ePBudweT1Qr1BUBAIAo0wmPxg4PuMEe5xgb24iGQaCgWzwMV-MVRIGKTGAqAAEqgEOkmFspKc0KCYhAKVSDvAkCh0PkXtx-qC0Ex-KhNjh8qS_nseWoKIIQfkCBA2HJlAjDsB-FSKCqybz8egAJJgdJLLbZdlgioSiAAGXYFKgZjYh1kxDUguFuBewyAA)| [After](https://echarts.apache.org/examples/zh/editor.html?version=PR-19035%40db2 …
=> fix(source): fix multi typed array detect error

src/chart/sunburst/SunburstPiece.ts, test/sunburst-label-align.html
fix align computed error caused by float precision. 
resolves https://github.com/apache/echarts/issues/18954
variable `radian`, not equal to `Math.PI / 2` ,but `-radian + Math.Pi * 2` is equal to `Math.PI * 1.5`, so this is a precision issue.
[Before](https://echarts.apache.org/examples/zh/editor.html?c=sunburst-drink&code=G4QwTgBAJiAuIQLwQNoCgIQN4cxARAHYgC2ApvgFwGBggYIz6g5Ab4A0um-AlrGSQMqwBPADYVqOPHnwBjAPZCZYKgQDEMAAxQAbAA58bCAF9WE6QAsOQqGDKEl6CZnEP2xckvyA_tUDzCoDAlQN4-gJ_agOlGgNymgN-KLPomXDz8wqLYUQ7ScgruymRqAOwAjACcUnrOmEZJ7FLmlta21PbFjmXJrgn4AGIA4rwAspH1JqBCAK4JOcZ97DF8giJKTuPlqYrU-MoAZnl5ZDmFjRIGu4Zj9XN9RKQtAArtACK98_gDw0qjBxPcU_Gzr5Ky8ksq6022yK83241K4xO9TObmWAEEYCQrrcjqdHiNUdDJnEZmJvgs_ulAVsdvNDAcIX0ocUYS1rmQyAAHVoyOR3cYPEBDDHfTjvHEJanQ35pZZrDYkkHg …
=> fix(sunburst): fix align error caused by float precision

src/core/echarts.ts, src/export/core.ts
Add missing types
Expose useful types, so it can be imported via `echarts`
#19003 
In order to import types that not publicly expose via `echarts`, the current behaviour is something like this 
```
import { SelectChangedPayload } from 'echarts/types/src/util/types'
```
After the change, users could import type in a correct way:
```
import { SelectChangedPayload } from 'echarts'
```
N.A.
=> feat(type): export `EChartsInitOpts` and more types for `echarts/core`

src/core/locale.ts
Fixed `t is undefined.` when `(document.documentElement.lang || navigator.language || (navigator as any).browserLanguage)` return `undefined`.
#19106
N.A.
=> fix(i18n): enhance default language fallback

src/chart/helper/createClipPathFromCoordSys.ts, test/clip-line-cap.html
Add an extra space to the clip-path `width`. This will prevent the unexpected clip.
- #19051
As the example https://codepen.io/rexskz/pen/WNLweyw shows, the rightmost position of the line that has `cap: 'round'` is clipped incorrectly, while the leftmost part is okay.
This issue only happens on the device with `devicePixelRatio >= 3`, and the chart canvas must have a special width.
The rightmost position of the line should not be clipped.
This is caused by a round-off error.
Let's see if the rect is:
```js
x = 80.8;      // float
y = 100;
width = 500.4; // float
height = 100;
// x + width = 581.2
```
Browsers will render the clip-path using `rect` but handle the value as integers, so the original code converts `x` and `width` to integers:
```js
x = …
```
=> fix(clip): add an extra space to the clip-path width to prevent unexpected clip. close #19051

src/util/types.ts
FYI, as per the [doc](https://echarts.apache.org/en/option.html#series-heatmap.data) null and undefined values are accepted in `series.data`. But the types do not allow it.
>Empty value: 
'-' or null or undefined or NaN can be used to describe that a data item does not exist (ps：not exist does not means its value is 0).
For example, line chart can break when encounter an empty value, and scatter chart do not display graphic elements for empty values.
This is  mostly a FYI PR, haven't done any dues on how this will affect the rest of the types. Tests etc.
=> Add nullables to OptionDataValue

src/chart/sunburst/SunburstPiece.ts
- [ √] bug fixing
This pr is used to fix a bug in the sunburst map where the lable position is incorrect when loaded counterclockwise
[Bug] When the sunburst is anticlockwise, the leaf node text displays the problem externally #19050
[https://github.com/apache/echarts/issues/19050](url)
- [√ ] The document should be updated later
N.A.
=> fix(sunburst): label rotation problem when anticlockwise

src/core/echarts.ts
The value of repairing the development environment `__ECHARTS__DEFAULT__RENDERER__` is undefined
N.A.
=> fix(core): fix potential NPE when reading default init options from global object in dev environment

src/i18n/langAR.ts
Adding **Arabic** language.
- Add new language.
- Add **Arabic** language file: **src/i18n/langAR.ts**
**- in progress...**
=> feat(i18n): add Arabic(AR) translation

src/label/labelGuideHelper.ts
solved problem:emphasis.labelLine not work in pie chart #19160
[https://github.com/apache/echarts/issues/19160](url)
#19160
label lines are not hidden when emphasis
When I select the blue section,label lines  are hidden when emphasis
N.A.
=> fix(labelLine):emphasis.labelLine not work in pie chart

src/i18n/langAR.ts, src/i18n/langCS.ts, src/i18n/langDE.ts, src/i18n/langEN.ts, src/i18n/langES.ts, src/i18n/langFI.ts, src/i18n/langFR.ts, src/i18n/langHU.ts, src/i18n/langIT.ts, src/i18n/langJA.ts, src/i18n/langKO.ts, src/i18n/langPL.ts, src/i18n/langPT-br.ts, src/i18n/langRO.ts, src/i18n/langRU.ts, src/i18n/langSI.ts, src/i18n/langTH.ts, src/i18n/langTR.ts, src/i18n/langUK.ts, src/i18n/langVI.ts, src/i18n/langZH.ts, src/visual/aria.ts
Support series type name in aria for custom series. And I found aria is missing for some i18n files so I added them.
#18054
Custom series type name is '自定义系列', which is not expected for languages other than Chinese.
Names in locale files are used.
N.A.
=> fix(aria): series type name for custom series

src/chart/sunburst/SunburstPiece.ts, test/sunburst-label-align.html, test/sunburst-label.html
Many cases were reported with sunburst's label rotation and several PRs trying to fix them have been merged (#18240, #18962, #19174). This PR refactored and simplified the related code, fixes the problem of #19127 and tested all reported cases and make sure the label rotation algorithm is as robust as possible.
- #19127
Label align is not syncing with rotation flipping, so the text is at the wrong position.
Use `needsFlip` to make sure this logic is the same with align and rotation.
Diff:
I've run the visual test with the last version 5.4.3 and the result is as expected. I've also tested all rotation values and clockwise values to make sure the text is always in the readable direction.
=> fix(sunburst): label rotation flipping

src/component/tooltip/TooltipHTMLContent.ts
1. Fix potential NPE when the parent node of the tooltip element doesn't exist.
2. clear timers when disposing
- Fix #19248
As the tooltip `dispose` is using `parentNode.removeChild` to remove the element itself and there is no non-null check, an NPE issue may occur.
<del>Switch to use the element's own `remove` API.</del>
Add a non-null check before calling `parentNode.removeChild`
N.A.
=> fix(tooltip): fix potential NPE when the parent node of the tooltip element doesn't exist

src/processor/dataSample.ts, src/util/types.ts, test/line-sampling.html
Add min-max sampler function
In some cases min-max sampling algorithm fits line data more naturally than the existing ones. For example, for a sine with a lot of data points min-max sampler is the best choice.
Example.
The original sine without sampling (200 000 data points).
Using 'average' sampler
Using 'lttb' sampler
Using 'max' sampler
Using 'min' sampler
Using new 'minmax' sampler
N.A.
=> feat(sampler): add min-max sampler function

src/chart/line/LineView.ts
Fix a bug brought by #18032, it may result in abnormal line animation.
- Fix #18942
[**Before**](https://echarts.apache.org/examples/editor.html?c=area-time-axis&version=5.4.3)
[**After**](https://echarts.apache.org/examples/editor.html?c=area-time-axis&version=PR-18960)
=> fix(line): fix line may cross in time axis when animation is enabled

src/chart/bar/BaseBarSeries.ts
Fixed the types of barMinWidth and barMaxWidth.
N.A.
=> Fixed the types of barMinWidth and barMaxWidth

src/component/axis/AxisBuilder.ts, src/coord/axisCommonTypes.ts, test/axis-align-lastLabel.html
In some cases, especially when the canvas size is limited, we wish to confine the axis labels to be within an area rather than may be outside of the canvas when the label text is long. In this PR, I proposed a way to set align/verticalAlign for the first and last labels so that we can make sure they are within the boundary of the grid area.
#19215
The first and last label may be too long to be displayed when the text is long and the canvas size is limited.
When setting `alignMinLabel: 'left', alignMaxLabel: 'right'` we can make sure the text is within the grid's width and the inner labels may hide when overlap.
N.A.
=> feat(label): support align for min/max labels

.github/workflows/.scripts/update-notice-year.js, .github/workflows/update-notice-year.yml
Add a scheduled workflow to update the NOTICE year on 1/1 00:00 (UTC+8) every year automatically.
N.A.
=> chore(workflow): add a scheduled workflow to update the NOTICE year automatically

.github/workflows/.scripts/update-notice-year.js
Fix the timezone error when getting new year by `new Date`
#19453
https://github.com/apache/echarts/actions/runs/7371451106/job/20058853427#step:3:1
N.A.
=> chore(workflow): fix timezone error when getting new year by `new Date`

src/core/echarts.ts, src/util/innerStore.ts, test/svg-ssr.html
#18381 set some required metadata for SVG elements but it didn't skip the undefined values, which caused the chart to generate many redundant attributes with the 'undefined' value.
In this PR, I add a precheck for `dataIndex`. It will skip to set SSR data if the `dataIndex` is not present.
Also, I fixed an unexpected assignment:
```diff
- childECData.ssrType === 'chart';
+ childECData.ssrType = 'chart';
```
Besides, I also added a non-null check in zrender. Please refer to ecomfe/zrender#1048.
#18381
| <img src="https://github.com/apache/echarts/assets/26999792/49affbab-c465-4908-9bbc-9850a3f1a16d" width="400"> | <img src="https://github.com/apache/echarts/assets/26999792/0fcc72b5-8ecd-4dcf-9f68-277669facde4" …
=> fix(ssr): remove redundant SVG attributes with `undefined` value

.github/workflows/ci.yml, .github/workflows/nightly-next.yml, .github/workflows/nightly.yml, .github/workflows/source-release.yml
This updates [actions/checkout](https://github.com/actions/checkout) in the GitHub Actions workflows to v4, it's current version.
Changelog:
> ## v4.1.0
> - Add support for partial checkout filters
>
> ## v4.0.0
> - Support fetching without the --progress option
> - Update to node20
N.A.
=> chore(workflow): update actions/checkout in workflows to v4

src/chart/bar/BaseBarSeries.ts, test/markArea.html
Partially fix (#18499). The case when some ticks are skipped due to overlapping is not fully fixed.
Fix the markArea position when axis has `axisTick.alignWithLabel: true`.
- Partially fix (#18499)
When some ticks are skipped due to overlapping (with dataZoom), there still remain to be a bug. This problem is not fixed in this PR because I can't think of an easy way to fix this. I added this test case. We should fix this later.
Wrong markArea position. [Demo](https://echarts.apache.org/examples/zh/editor.html?code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdPqViNceORHoBrIqnvoA9D9gAhAGwAO7aVHAABowANhCs0KoQYNoAMowARlQxkbD4sJFgHEqRPGThsAC2jBxuWBxUjLARAngOYAVmYLmWVBjU9CwCMeT8pLHxiclpmd …
=> fix(marker): fix markArea position when axis is with `alignWithLabel`

src/util/states.ts
ecomfe/zrender#999 moved the `liftColor` function to zrender, this PR is to follow that change and import it from zrender.
N.A.
=> refactor(util): import `liftColor` function from zrender

src/component/legend/LegendView.ts, src/component/tooltip/TooltipView.ts, src/core/echarts.ts
fix a bug introduced by #18381
#18381 brings a bug that hovering the legend will show tooltips.
Tooltip shows when hovering the legend.
Tooltip not shows when hovering the legend.
N.A.
=> fix(ssr): hovering legend items should not trigger tooltip

build/build.js, build/config.js, package.README.md, package.json
Previous issue https://github.com/apache/echarts/pull/19513
This PR fixes:
+ (1) Mistake in package.json "exports"."require".
+ (2) Add entry for dist/** for "file extension not specified" usage. 
+ (3) Add `dist/echarts.esm.mjs` (after build). Originally there is only `dist/echarts.esm.js`, which is a ESM file. Since `dist/package.json` with `{"type": "commonjs"}` is added, webpack5 can not recognize it as ESM by default. This is a breaking change. So add `dist/echarts.esm.mjs` for the uses that get that trouble.
=> Fix: esm issue 

src/component/toolbox/feature/SaveAsImage.ts
Fix an unexpected replacement in https://github.com/apache/echarts/commit/53babd2b4c83e875f8df6c370b356d6b44c1919c#diff-0b91602cf047a98c67d6c4edaacbfa7399c8e0d2d4564b83ece8419d144aea84R64
\- Should use the `typeof` operator to avoid uncaught reference error.
- #16318
N.A.
=> fix(toolbox): use `typeof` operator rather than `isFunction` util to detect if `MouseEvent` object is supported

.github/workflows/ci.yml, .github/workflows/pr-preview.yml, .github/workflows/source-release.yml, .github/workflows/stale.yml
Update workflow dependencies to address the deprecation warnings. 
N.A.
=> chore: update workflow deps

src/component/helper/MapDraw.ts, test/map-china.html
- [] new feature
The georoam event of the map component supports the totalZoom parameter, which is used to do some interaction with the linkage business when the chart is resized
N.A.
=> georoam supports the totalZoom parameter

src/data/helper/dataValueHelper.ts, src/data/helper/sourceHelper.ts
- Replaces global `isFinite` with `Number.isFinite` and unary (`+`) with `Number()` conversion so that a simple chart doesn't blow up when passing in a `BigInt`
- Related to #19237 (addresses a small part of it)
When passing a `BigInt` data column to a chart, the chart blows up.
```
Uncaught TypeError: Cannot convert a BigInt value to a number
at isFinite (<anonymous>)
at detectValue (chunk-TNIQ5HHQ.js?v=9ea597be:5513:25)
at doGuessOrdinal (chunk-TNIQ5HHQ.js?v=9ea597be:5494:21)
at guessOrdinal (chunk-TNIQ5HHQ.js?v=9ea597be:5434:10)
at new SourceImpl2 (chunk-TNIQ5HHQ.js?v=9ea597be:5538:17)
at createSource (chunk-TNIQ5HHQ.js?v=9ea597be:5555:16)
```
👇 
This is happens because of the way `isFinite`, `isNaN`, and `+` (unary operator) coerces the values. …
=> fix: detectValue & parseDataValue not crashing with BigInt

src/visual/aria.ts, test/node/ssr.js
Skip setting aria label attribute when in SSR mode.
#19191: <q>[Bug] SVG ARIA doesn’t work with SSR</q>
`aria-label` was set on the DOM element, but in SSR there is no DOM element, so it would throw when enabling `aria` or `locals` in options when using SSR, because the `dom` variable in code is `null`.
Also, this makes the last example in [this release note](https://echarts.apache.org/handbook/en/basics/release-note/v5-feature/) (Two color locals) not working in SSR.
No aria label was added, but locals are working in SSR.
N.A.
=> fix(aria): avoid throwing error in SSR mode (#19191)

src/util/time.ts, test/ut/spec/util/time.test.ts
I added a meridian template to the time format.
There wasn't a template to show the meridian.
Now it's possible to use the template {a} | {A} to show the meridian on the time formatting
N.A.
=> feat(time): add meridian template {a}/{A}

src/component/marker/MarkerModel.ts, test/markPoint.html
Fix a long-term bug that marker label formatter can't get series information like `seriesName`, `seriesType`, and `seriesId` - This causes formatter template keywords like `{a}` not to work.
- Resolves #19896
https://echarts.apache.org/examples/editor.html?c=bar-rich-text&version=PR-19898
| Before | ![Before](https://github.com/apache/echarts/assets/26999792/59e7d809-8d53-4cec-b776-3e42eb4afee4) |
| After | ![After](https://github.com/apache/echarts/assets/26999792/e5da286b-d960-4026-bff3-07d3fcb8f05f) |
Please refer to the second case in `test/markPoint.html`
=> fix(marker): fix marker label formatter can't get series information

src/chart/treemap/TreemapSeries.ts, src/chart/treemap/TreemapView.ts, test/treemap-scaleLimit.html
Add `scaleLimit` option to allow limiting the zooming in treemap.
[#14599](https://github.com/apache/echarts/issues/14599)
We don't have any limitation for zooming in treemap.
Support `scaleLimit` in treemap series, as graph series, tree series, geo component did.
Like [scaleLimit in geo](https://echarts.apache.org/en/option.html#geo.scaleLimit)
`treemap-scaleLimit.html`
=> feat(treemap): add scaleLimit to limit the zooming. close #14599

src/coord/axisCommonTypes.ts, src/coord/axisTickLabelBuilder.ts, test/axis-customTicks.html
Add option `customValues` to `axisTick` and `axisLabel`, which allow the user to specify tick/label positions.
This PR is based on #13636 . Since it's a long time since the opening of this PR, I made a few adjustment based on the original commit, with full regards to the contribution to @dvdkon 's contribution.
#13627
See issue #13627 
The new option allows for completely custom tick/label positions, for example:
```js
xAxis: {
type: 'value',
axisLabel: {
customValues: [0, 4, 7, 8, 9]
},
axisTick: {
alignWithLabel: true,
customValues: [0, 0.5, 1, 1.5, 2, 8, 9]
},
}
```
In axis:
- `axisTick.customValues: (string | number | Date)[]`
- `axisLabel.customValues: (string | number | Date)[]`
Array of axis values on which a tick/label will be present …
=> feat(axis): custom axis tick/label positions

.github/workflows/pr-preview.yml, .github/workflows/teardown-pr-preview.yml
The action tool [maintain-one-comment](https://github.com/actions-cool/maintain-one-comment) that we are using is quite inactive, so I forked it and will add features as needed and keep maintaining the fork.
=> chore(workflow): use forked workflow deps for timely update

src/visual/aria.ts
Add role="region" on div tag when aria option is true to allow the aria-label property on the div
#20034
When aria option was true it would add aria-label to a div tag without a role. aria-label should only be added to interactive elements so it would fail Accessibility tests like Lighthouse's.
Now with role="region" the aria-label is allowed on the element. 
N.A.
=> feat: add role region to div tag when aria: true

.vscode/settings.json
In case some developers use a typescript version outside the workspace, which may be different from the fixed typescript version in package.json, it's better to enable a prompt.
N.A.
=> chore: enable prompt to use typescript from workspace

src/chart/line/LineView.ts
Prebind the context of the `_changePolyState` function to the current instance of `LineView` rather than create a new function to reduce runtime memory cost.
- Resolves #20151
| [Before](https://echarts.apache.org/examples/editor.html?code=G4QwTgBARiDOCmEC8EDUA7eB3CAREALvABQBMADAIwAsANBAJz0DMAlANwBQokA9pvgCeyCKWoQAVBGYA2cuUkRK88lx4QAJoUQoA2gF014TYRAjdAWUIALAHRgQ6DbwC2xVosoBWcoe7H0XhwUTBx8ImIYBA5OADMAV3QAYwIAS34IEA0NcJBiWGtU2IIPAG9OCAhA4IhdatsAc3gCADF4gBt2gE14cHd6eqaCC34Ca3c0JQGgxubwklZ9WwArXlT0YgByAHpNmMqtIlsAB3iC4mr9kwIQE7Px4isx-0dnNw8AWghyW2oPKWUk0OIF0wNs7Xg6AaYwgX0o-iuRQg-UKxTKFUq13gtgKRQI7i4mOut1xxQJGIAvhjqiJQnhtMQMNh6RFLpN-PAhDEqbFeJBiOpUiJKOwIEKADxKeSi1KoVDoypZHKmclU3jHNIZFDlSoADwAgrrUrAAFwQHWYgiCY7wM2bJLaBp8wSbWgYypQXiJLRgQQAcRAxzNsRA7QQbqJwLNh3g …
=> perf(line): reduce runtime memory cost

src/component/axis/CartesianAxisView.ts, src/coord/Axis.ts, src/coord/axisCommonTypes.ts, src/coord/axisDefault.ts, test/axis-splitLine.html
添加"删除坐标轴指定刻度上的分隔线"的功能
Add feature `showMinLine` `showMaxLine` to splitline in coordinate axis
- #20110 
用户无法自定义删除任意刻度上的分割线
当 xAxis 选项中的 splitline 属性与 yAxis 选项中的 axisLine 属性同时设置时，两条线会在 yAxis 轴线所在的位置重叠
User cannot customize the deletion of dividing lines on any scale.
While splitline attr in xAxis options and axisLine atrr in yAxis options set concurrently, two lines from each other overlapper in the position where yAxis axisline lies.
用户可以将 `showMinLine` 或 `showMaxLine` 设置为 `false`，从而删除第一条或最后一条分割线
User can set the `showMinLine`/ `showMaxLine` be `false`  to delete the first/last split line.
```javascript
xAxis: {
type: 'category',
data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
splitLine: {
show: true,
showMinLine: false,  // do not show the …
```
=> feature(axis): add showMin/MaxLine to splitline in coordinate axis

src/chart/pie/labelLayout.ts
[#20070](https://github.com/apache/echarts/issues/20070) Missing pie chart label display
When set option as: 
```js
option = {
tooltip: { trigger: 'item', formatter: '{b}: {c} ({d}%)' },
series: [
{
name: 'Access From',
type: 'pie',
radius: ['45%', '60%'],
labelLine: { length: 30 },
label: {
formatter: '{a|{a}} {abg|}\n{hr|}\n {b|{b}：}{c} {per|{d}%} ',
backgroundColor: '#F6F8FC',
borderColor: '#8C8D8E',
borderWidth: 1,
borderRadius: 4,
rich: {
a: { color: '#6E7079', lineHeight: 22, align: 'center' },
hr: {
borderColor: '#8C8D8E',
width: '100%',
borderWidth: 1,
height: 0
},
b: {
color: '#4C5058',
fontSize: 14,
fontWeight: 'bold',
lineHeight: 33
},
per: {
color: '#fff',
backgroundColor: '#4C5058',
padding: [3, 4],
borderRadius: 4
}
}
},
labelLayout: { …
```
=> fix(pie): fix some labels may not show

src/coord/axisTickLabelBuilder.ts, test/axis-customTicks.html
When using dataZoom, the ticks may overflow grid area in some cases.
#20185
Ticks may go outside of the grid.
Ticks don't go outside the grid.
N.A.
=> fix(axis): fix ticks overflowing grid area with dataZoom

src/chart/treemap/TreemapSeries.ts, src/chart/treemap/TreemapView.ts, test/treemap-cursor.html
This pull request is in the type of: 
Adding custom cursor properties for Treemap
- #13632 
In treemap, there is no way to customize the cursor style through cursor, and it can only default to "pointer"
Users can set the cursor style in option like other series graph
```javascript
series: [
{
name: 'TreeMap Cursor',
type: 'treemap',
label: ... ,
breadcrumb: ... ,
levels: ... ,
cursor:'crosshair',  // it should be able to set crosshair for treemap
data: 
}
]
```
N.A.
=> feature(treemap): add custom cursor properties for treemap

src/util/types.ts, src/visual/aria.ts, test/ut/spec/series/aria-columns-exclude.test.ts
Allows excluding data in aria-label
All data was present in the aria-label. My use case was for a map chart, where the coordinates should be excluded.
Add column indexes to be excluded to aria.data.excludeDataId and they will not appear in the data in aria.label.
N.A.
=> feat(aria): allows excluding data in aria-label

src/coord/axisHelper.ts
Fix bar series bandWidth with axis typed with `'time'` and `inverse: true`.
#20068
Wrong bandWidth:
Correct bandWidth:
N.A.
=> fix(time): fix bar bandWidth with inversed time axis

src/chart/gauge/GaugeView.ts
When `max` of a gauge is negative, the `z2` calculated is also negative. Thus the axisLine is on top of the progress bar. This PR fixes how `z2` is calculated to ensure it is always non-negative.
fix #20097
The progress bar is beneath the axisLine.
N.A.
=> fix(gauge): fix z2 is negative when maxVal is negative

src/chart/treemap/TreemapView.ts
https://github.com/apache/echarts/commit/f7e61f20c1f91431d4ef4f70b5ecd392dc764a13 moves `RoamController` to a different file so the importing path changes. However, by the time #18304 was merged, the above change was only in the `next/v6` release so that the importing path had an error on these branches.
N.A.
=> fix(roam): fix RoamControllerHost importing path

src/component/dataZoom/SliderZoomView.ts
Change cursor icon to more intuitive 'move', for dataZoom slider moveHandle
- #20303
The Move/Drag icon is not intuitive, and it makes it difficult to know whether you're busy resizing or dragging, when the mouse is nearby the edge.
| Original Move/Drag icon | New Move/Drag icon | 
|--------|-------|
|  ![bad_move](https://github.com/user-attachments/assets/2f20f190-a06a-4aac-953a-46eed6391fa9)  | ![suggested_move](https://github.com/user-attachments/assets/22796011-df87-4a8b-ba5c-fad830354116)  |
N.A.
=> feat(dataZoom): change moveHandler cursor icon to move

src/i18n/langPT-br.ts
Improve pt-BR translation.
N.A.
=> feat(i18n): improve pt-BR translation

src/chart/helper/whiskerBoxCommon.ts, test/boxplot-category.html
Fixes issue with series.encode for boxplot when category axis is used.
#20319 
When a category axis is used for a boxplot series, an ordinalValue is always inserted to the series.data which breaks any encoding rules. if the category axis does not set it's own data then the axis labels will be the integer ordinalValue.
Now if an encode rule is applied for the associated axis (x/y) then the ordinalValue is not inserted and the encoding rules work as expected.
test/boxplot-category.html added to show visual example.
=> fix(boxplot) correctly handle series.encode with category axis

src/chart/sankey/SankeySeries.ts, test/sankey.html
#20336
getInitialData function may return uncatched undefined
Catch undefined data like the other graph chart
N.A.
=> fix(sankey): avoid throwing errors when the `links` / `nodes` / `levels` option is undefined

src/chart/bar/PictorialBarView.ts, test/pictorial-zero-value.html
When data value is 0, there was a bug that the item symbols are flipped. 
#20260
Symbol filpped.
Symbol not flipped.
N.A.
=> fix(pictorialBar): symbol should not flip with zero data

src/component/visualMap/ContinuousView.ts, test/visualMap-continuous.html, test/visualMap-layout.html
It switches visualMap handle label vertical align property basing on the visual map orientation and layout.
- #20248  
Label for handle at minimum position collides with the handle. The reason is that the distance between label and handle is based on the handle size and it changes depending on handle position. Currently label has always verticalAlign set to "middle", which is the cause of the collision (when distance is less than the half of the label height, the items collide). For labels below, vertical align could be "top" and for labels above, vertical align could be "bottom".
The labels below maximum range in horizontal visualMap get a slight offset to avoid collision.
This solution is not perfect, as the calculation method is different for …
=> fix(visualMap): handle label collides with horizontal size visualMap

src/component/tooltip/TooltipHTMLContent.ts
- Fix #20335 
- Optional chaining for tooltip `offsetWidth` and `offsetHeight`
N.A.
=> fix(tooltip): fix potential NPE when setting option with `notMerge` strategy

src/data/DataStore.ts, src/data/SeriesData.ts, src/processor/dataSample.ts
This fixes the minmax sampling behaviour to follow the standard as described [here](https://www.ni.com/docs/en-US/bundle/labview/page/memory-management-for-large-data-sets.html#d87745e217).
No open issue, but the problem was discussed in the original PR for this feature: https://github.com/apache/echarts/pull/19279#issuecomment-2131424868
I generated some fake data, 16000 data points for each graph (green random walk, yellow sine wave, and blue pseudo-random).
I added two artificial "spikes" for each graph: a downward spike at index 7000, and an upward spike at index 9000.
| No downsampling | Original minmax downsampling implementation |
|----------|-----------|
| ![NoDownsampling_16kpoints_across_1604pixels](https://github.com/user-attachments/assets/d …
=> fix(sample): fix minmax sampling behaviour

src/component/tooltip/TooltipHTMLContent.ts, src/component/tooltip/tooltipMarkup.ts, test/tooltip-textStyle-lineHeight.html
#20391 
lineHeight not work
add line-height in css
N.A.
=> fix(tooltip): Tooltip textStyle lineHeight does not work in default 

src/chart/line/LineView.ts, test/line-step.html
Resolves #20021
areaStyle with stepped line series and connectNull is not correct.
No skewing in areaStyle.
N.A.
=> fix(line): fix areaStyle skewing in stepped line series and incorrect connectNull behavior

package-lock.json, package.json
Relax dependency specifier of tslib
I was testing my library with vite v6.beta, and found that tslib@2.3.0 did not work; later version of tslib did work.
echarts now allows users to pick their own version of tslib - so a. it now works with vite v6 and b. users aren't unecessarily shipping two copies of tslib
N.A.
=> Relax tslib requirement specifier

src/component/calendar/CalendarView.ts, test/calendar-simple.html
Add `silent` option for `dayLabel`/`monthLabel`/`yearLabel` to allow the users to disable the label interaction.
[Demo](https://echarts.apache.org/examples/editor.html?c=calendar-simple&code=GYVwdgxgLglg9mABAcwKZQGowE5RAQwBsARfKfACgE9V9sBKRAbwChFEIEBnKRAEzKpEAXkQBqVBAAWdKFwB0sALap5ABzpdU1WtnGIA5AFoADAEZTZg_QDcbDt16owfEeMkzcC5ao3YtOnT6xmYATEYAzFa29pxgPPz4VAAqMCpuEQBsJiaIAFSIoQAs-YhmOSZ27HEJAuRuANoAulWIwHB6FIToiD5udag2vWlCADyiznxDfWKiAikjjKzs7HX46iBcUhQN9iuIHrLeI_Lt2EpkFD4ANIZMVA9UAL5GTACyby9MfHxPBrfAIhaejXPYrN5kKSnQhwDoUCFQKHYfAuOBKCiMArlCr0MFNGLsJ72bDoEDYJBrOxEuBqWAINzLRAANxgXAIhAhagAXMwwVs4AB3HmAwhaUH7JQwMA8kzilYXAAePOxOXsTzlECIkzoPMZ7GRYDQPIMoXMAHZ_mD5gAZfAAI1QhF1YPYXBg3TAUB5UGwIFQYPVYKUCERtodTt5-1d7ucXt6vv9-0D-xodDDjudUcQbo9cZ9foDarlWmwMFQXEzKygVDUqG …
=> feat(calendar): add `silent` option for `dayLabel`/`monthLabel`/`yearLabel`

src/data/SeriesData.ts
Fix potential NPE in the `SeriesData#rawIndexOf` function
- Resolves #20532
N.A.
=> fix(data): fix potential NPE in the `SeriesData#rawIndexOf` function

package-lock.json, package.json, src/component/axis/AxisBuilder.ts, test/axisLabel.html
Support tooltip for the axis label. It's useful for the case in which the axis label is truncated for long text and hope to show the full text when hovering on the label.
- #11903
- #15299
- #16228
No tooltip for showing the full text of a truncated axis label. The developer has to simulate a tooltip via listening to the mouse event like https://codepen.io/plainheart/pen/jOGBrmJ.
Please refer to the last test case in `test/axisLabel.html`.
=> feat(axis): support tooltip for axis label

test/ut/spec/series/aria-columns-exclude.test.ts
Fix the doc of #20218.
It should be `aria.label.data.excludeDimensionId` instead of `aria.data.excludeDimensionId`. The old test case can pass but it's because it inherited from the parent.
N.A.
=> test(aria): fix test case of #20218

src/component/visualMap/PiecewiseView.ts, test/visualMap-selectMode.html
#20533
cursor is `pointer `on `selectedMode: false`
cursor is `default `on `selectedMode: false`
N.A.
=> fix(visualMap): cursor is pointer on selectedMode=false

src/chart/map/MapSeries.ts, src/component/helper/MapDraw.ts, src/coord/geo/GeoModel.ts, src/coord/geo/Region.ts, src/coord/geo/geoCreator.ts, src/data/SeriesData.ts, test/geo-map.html, test/map-nested.html
This PR supersedes #20561. Apply `echartsStyle` in the Model instead of View.
[Demo](https://echarts.apache.org/examples/editor.html?version=PR-20564&code=LYTwwgFghgTgLgOgM4QPYHcAyqoBMCWAdgOYAUAlANwBQAJAsQKZykBKA8uwCoD6ACgEEuACQAEAalEByAPS4ocKDKhIkzGU1QyAqgGUBCAFZJUhKQBpRAMwCuhAMZx8p0aRtIoAKROFyogN7UoqKgkLCIEPi4jNh4RGRUQaLuXj4IVowKNjCMSADaAAwAuggADjCopYzw-LkIjPbQ8Ei6cCAANoyiALwBScH4cIzArR2MAFx9wdOisJlgqO2oMJNSObhS_aIAvkm7wSnepumZcNm5eQAsJeWV1U51DU1wLW2dPVPTg8OjnZOBM2CACNltEYFwQFVJnkAKyWGFFcxbYGg6oLJYraRA9o2RgWZGiEEwMEAdSicAgkwATFt9jskk9wkgEDliPgkEMYABZKClUhSPQCCzJDxHQiWAHTATtFQAayg_wJnSscEmAFoAIwAZg1SMBojglWpcIJ6HJlNEGphtL102EUHQUHw-EV-uVqtEmo1BVtM0NpWpAA5fdMzbgKZNrTNtiGpHxcfBUKJWPh7KgpK7Ae71QB2ABsIeC_upBdN5uptL2iWClScLl6kqLgz-nz9jAAHh6BfpRHxKjYZXXCKIAK …
=> feat(geo): support styling region in original GeoJSON data

test/runTest/cli.js, test/runTest/client/client.js, test/runTest/client/index.html, test/runTest/server.js, test/runTest/store.js, test/runTest/util.js
Supports using PRs on GitHub in visual tests.
We can use only a released version or nightly build to do visual tests.
We can input a PR id on GitHub to do the visual test and the artifact of PR preview of `dist/echarts.js` will be used. This is helpful because I want to compare the changes of a v6 feature and want to compare with v6 branch.
N.A.
=> test: visual test support compare with a PR id

src/chart/heatmap/HeatmapView.ts, test/calendar-heatmap2.html
Fix the bug that labels not in the calendar range are unexpectedly displayed, as a supplement fix of #12991.
[Demo](https://echarts.apache.org/examples/editor.html?code=PYBwLglsB2AEC8sDeAoWsBuEDOBXAhgDYCy-IAXMmurNgBbADulAZkdgKYA016AthGiUADDxqw--AB6UAjMIXDqAXzGwAxkQ7QAJvgBOlVOP35oAcw6UA5ACZhsgGwBaB9ZVrO-iB2xHesGAAniBWsNZ0HPhgkiDWaujqwMD6OoLRHADKQdhgHHw2moTaevrxAXpg-JQA2gHoNXYOLg6uAKzxsG0KALoJNI32Tq6yzk6d8sJ99bCDzSPO9p2OAOxT_Q1Nw622K50AzL0bs1sttiOdABy9AdPihPgARhyE_uLo9EyUYPq43DMYDj6SBFACChAg5iE4TAoHK71gREh0OsxRYYHh7xYKUkYDy-gAFCADPg-NgAJRUBHoCAsWAEgCExNMZIAdBgiH8alNWbkDGBsAB1CBgOgE04XcmU4zU9D6DhgXD6ODWACqADkAKIADQACpqAMIAFU1ABFYAAZUEAIU1FsyDMd1gA3DN0Mo3bB5YrleEXTNVDMkoQUjZ5TpMeJsdAwIKOJC6GAbI9gIQI8do2BMhAAF5hewBD3ulDKZ1AA&version=PR-20699)
Fix #20690
One …
=> fix(heatmap): fix labels not in calendar range are unexpectedly displayed

src/component/title/install.ts
Title text style type should not include string.
doc:
ts:
#20799 
N.A.
=> fix(title): title text style width type should not include string #20799

src/chart/helper/Line.ts, src/chart/helper/Symbol.ts, src/component/marker/MarkAreaModel.ts, src/component/marker/MarkAreaView.ts, src/component/marker/MarkLineModel.ts, src/component/marker/MarkLineView.ts, src/component/marker/MarkPointModel.ts, src/component/marker/MarkPointView.ts, src/data/SeriesData.ts, test/marker-z2.html
#6691 
markPoint markLine markArea add z2 option to support change level.
N.A.
=> feat(marker): markPoint markLine markArea add z2 option to support change level

src/component/dataZoom/SliderZoomView.ts
- minMaxSpan could restrict brushSelect
fixed #20807 
N.A.
=> fix(dataZoom): restrict range on brushEnd

src/component/legend/LegendModel.ts, src/component/legend/LegendView.ts, test/legend-action.html
add legend event `legendmouseover` `legendmouseout`
#18144 
Stop data carousel when mouse hover on legend must customizing legend elements with HTML
see demo:
https://codepen.io/plainheart/pen/xxJRdam
Stop data carousel with legend event `legendmouseover` `legendmouseout`
see demo:
https://stackblitz.com/edit/js-q9vzb5?file=index.js
N.A.
=> feat(legend): legend support triggerEvent (#18144)

src/core/echarts.ts
Remove the check for SVG support in the `getSvgDataURL` function since SVG based on Virtual DOM has been supported since v5.3.0.
N.A.
=> fix(svg): remove SVG support check in `getSvgDataURL`

src/chart/pie/PieView.ts, test/pie-label.html
This fixes an error introduced in #14017, which gets label position from series model rather than data item model.
- Resolves #20904
- Resolves #20905
Please refer to the 9th test case in `test/pie-label.html`
=> fix(pie): fix labelLine may be not removed and cause error when single label position is not in outside

src/chart/bar/BarSeries.ts
Fix https://github.com/apache/echarts/pull/17078#discussion_r1648347405 by removing the unused `startValue` option from the `BarSeriesOption` interface. This option is for the axis rather than the bar series.
N.A.
=> fix(bar): remove unused `startValue` option from the `BarSeriesOption` interface

src/animation/customGraphicTransition.ts
Fix potential NPE when applying leave transition on an element without a parent element.
- Fix #20917
N.A.
=> fix(custom): fix potential NPE when applying leave transition

src/component/visualMap/ContinuousView.ts, src/component/visualMap/PiecewiseView.ts, test/visualMap-pieces.html
Fix some text style (`width/overflow/align/verticalAlign...`) can't work on visualMap (piecewise & continuous). This PR also improves the previous fix in #16679.
- Resolves #20956
- Resolves #18882
- Resolves #15644
See `test/visualMap-pieces.html`
=> fix(visualMap): fix some text style can't work on visualMap

src/processor/dataStack.ts, src/util/types.ts, test/bar-stack-reverse.html
Add support for reversing stack order in stacked charts through a new `stackOrder` option.
https://github.com/apache/echarts/issues/20983
Previously, stacked charts (bar, line, area) only supported the default stacking order where series are stacked in the order they are defined. 
Users had no way to reverse the visual stacking order without manually reordering their series data, which could be inconvenient.
Now users can set `stackOrder: 'seriesDesc'` on any series in a stack group to reverse the visual stacking order. The feature works by:
1. Adding a new `stackOrder` option to `SeriesStackOptionMixin` with values `'seriesAsc'` (default) or `'seriesDesc'`
2. Modifying the data stack processor to check for the `stackOrder` setting and reverse the …
=> feat(stack): able to reverse the stack order

src/chart/custom/CustomView.ts
Revert checking `buildPath` from https://github.com/apache/echarts/pull/20402/commits/d2c05a7656828a28d96e0e6ee28c94c9af0221ca.
I forgot why I added this code, probably to fix the cause where `path` is a `Path` instance rather than a plain object, in the case of custom [stage chart](https://github.com/apache/echarts-custom-series/tree/main/custom-series/stage). I checked it's not depended by the stage chart and visual tests don't fail without this change so I decide to revert it.
Nothing is expected to be different.
N.A.
=> fix(buildPath): revert checking buildPath

src/component/marker/MarkPointView.ts, src/component/marker/markerHelper.ts, test/dataZoom-action.html
#20166 breaks the case of `marker-case.html`, where marker is used in pie series and has no coordinate.
Fix the order of importing files in `test/dataZoom-action.html`, which is not related to this issue but fixed together for convenience. It seems `lib/config.js` should be imported before `lib/simpleRequire.js`, otherwise, the local echarts file cannot be found:
No error message and chart is rendered as expected.
N.A.
=> fix(marker): fix bug of #20166

src/component/dataZoom/SliderZoomView.ts
#16978 breaks the case of `test/tooltip-axisPointer.html`, where the first `otherCoord` is NaN.
DataZoom is displayed at the wrong position.
N.A.
=> fix(dataZoom): fix the case when first value is NaN, relates to #16978

package-lock.json, package.json, src/util/model.ts
=> chore: use zrender#next and remove unused import

src/theme/dark.ts
When `inRange.color` was defined in dark theme, it may break the case where color isn't intended to use visualMap.
v6 dark theme breaks the example at https://echarts.apache.org/examples/zh/editor.html?c=scatter-aqi-color .
N.A.
=> fix(visualMap): fix dark mode should not provide inRange

src/i18n/langEL.ts, test/lang.html
Adds Greek (EL) locale support with translations for all ECharts UI elements
Fixes issue #21118 
ECharts was missing Greek (EL) locale
This pull request adds Greek (EL) locale
N.A.
=> feat(i18n): add Greek locale. Closes #21118

src/chart/radar/RadarView.ts, test/radar.html
=> fix: add symbolPath opacity. close #21074

src/coord/radar/Radar.ts, src/coord/radar/RadarModel.ts, test/radar-clockwise-interactive.html, test/radar-clockwise.html
This pull request introduces support for configuring the direction of radar charts by adding a `clockwise` option.
closes #5190
The radar chart indicator axis can only be arranged anti-clockwise; the original data must be modified to change it to clockwise.
We can make the radar chart render in a clockwise direction using `options.radar.clockwise` (boolean).
- test/radar-clockwise.html
- test/radar-clockwise-interactive.html
=> feat(radar): add clockwise options support

src/chart/line/LineView.ts, test/line-area-empty-dimension-name.html
Fix line area rendering issue when dataset dimension name is empty string.
- #20756
When `dataset.dimensions[].name` is set to an empty string `""`, the line chart with `areaStyle` renders incorrectly.
**Root cause:** In `getStackedOnPoints` function, empty string dimension name fails truthiness check:
```typescript
if (!dataCoordInfo.valueDim) {  // Empty string "" is falsy
return [];
}
```
This causes the function to return empty `stackedOnPoints` array, breaking area rendering.
Changed the check to only reject `null`/`undefined` values:
```typescript
if (dataCoordInfo.valueDim == null) {  // Only reject null/undefined
return [];
}
```
Empty string dimension names are now treated as valid dimension names for area rendering.
=> fix(dataset): wrong area when dimension name is empty string

src/chart/gauge/GaugeView.ts, test/gauge-progress.html
Apply correct color to gauge chart progress when set to 'auto' in svg renderer.
- fixes #19884
See the issue for more details.
N.A.
=> feat(gauge): progress.color supports 'auto'

src/component/dataZoom/SliderZoomView.ts, test/dataZoom-single-datapoint.html
Fix position of the dataZoom control when the series has only one data point. Please refer to the linked issue for more details.
- #21195 
=> fix(dataZoom): fix wrong position of the dataZoom when the series has only one data point
